== Game Structure
NOTE: References to the male gender in the rules with respect to referees, team members, officials, etc. are for simplification and apply to both males and females.

=== Impartial Roles
To play an official match in the Small Size League, four impartial roles must be filled:

* the <<Referee, referee>>
* the <<Assistant Referee, assistant referee>>
* the <<Game Controller Operator, game controller operator>>
* the <<Vision Exptert, vision expert>>

Usually, these roles are filled by two non-playing teams, with one team providing the <<Referee, referee>> and the <<Game Controller Operator, game controller operator>> and the other team providing the <<Assistant Referee, assistant referee>> and the <<Vision Exptert, vision expert>>. The assignment of the roles is up to the organizing committee.

Every participating team is required to be able to provide enough people who are familiar with these roles.

==== Referee
Each match is controlled by the referee. He has full authority to enforce the rules of the Small Size League in connection with the match to which he has been appointed. The referee is encouraged to use the designated walking area next to the field (see <<Field Setup>>).

The referee is assisted by the <<Automatic Referee, automatic referee>> software. The human referee is allowed to override any decision made by the automatic referee software.

The decisions of the referee regarding facts connected with play are final. The referee may only change a decision on realising that it is incorrect or, at his discretion, on the
advice of an assistant referee, provided that he has not restarted play.

The referee is not held liable for any kind of injury suffered by an official or spectator, any damage to property of any kind nor any other loss suffered by an individual, club, company, association, or other body.

The <<Robot Handler, robot handler>> is the only team member that may talk to the referee.

.Duties

* The referee ensures a safe match for all humans and robots
* The referee ensures a fair match according to the rules of the Small Size League
* The referee ensures that there is no interference by unauthorized persons or team members
* The referee or assistant referee places the ball for <<Kick-Off, kick-offs>> and <<Penalty Kick, penalties>> (division A) or after every <<Stopping The Game, stoppage>> (division B). Subsequently, the referee resumes the match.

==== Assistant Referee
The assistant referee supports the referee whereever he can. He is encouraged to use the designated walking area next to the field (see <<Field Setup>>), opposite the referee.

No team members are allowed to talk to the assistant referee.

.Duties

* The assistant referee indicates when misconduct or any other incident has occurred out of the view of the referee
* The assistant referee discusses unclear situations with the referee
* The referee or assistant referee places the ball for <<Kick-Off, kick-offs>> and <<Penalty Kick, penalties>> (division A) or after every <<Stopping The Game, stoppage>> (division B)


==== Game Controller Operator
During a match, the game controller operator uses the <<Game Controller, game controller software>> as an interface between the <<Referee, referee>> and the team software.

No team members are allowed to talk to the game controller operator.

TODO

==== Vision Expert
During a match, the vision expert is in charge of the <<Vision, shared vision system>> on the field.

Team members are generally advised not to talk to the vision expert, unless they experience major vision problems.

.Duties

* The vision expert checks the vision hardware and reports any kind of hardware problems to the technicall committee
* The vision expert monitors the shared vision system during the match and reports any kind of problems to the referee instantly
* The vision expert recalibrates the vision system if the referee deems it necessary

=== Team-Specific Roles

==== Robot Handler
Before the start of the match, every team has to designate one robot handler. The robot handler represents the team during the match.

.Duties
* The robot handler helps <<Match Preparation, preparing the match>>.
* The robot handler asks the referee for <<Timeouts, timeouts>> if necessary.
* The robot handler asks the referee for the permission to exchange a robot in the next stoppage and exchanges the robots (see <<Exchanging Robots>>).
* The robot handler voices concerns of the team (for example network issues or vision problems).

=== Match Preparation
All people that fill a role in the match (<<Impartial Roles, impartial>> or <<Team-Specific Roles, team-specific>>) have to be ready at least 10 minutes before the match starts.

==== Game Result Sheet
Before the match starts, the <<Referee, referee>> obtains a game result sheet from the organizing committee. After the game, the referee fills in the final score, collects the required signatures and submits the sheet to the organizing committee.

NOTE: While obtaining the game result sheet, the referee can also take an official <<Ball, ball>> and referee equipment such as a whistle or red and yellow cards (if provided).

==== Testing The Network
==== Choosing Colors, Side And Kick-Off
Chapter 4.5, 8.1

==== Choosing Keeper Id

=== Game Stages
==== Overview
Chapter 7.1, Appendix A.1
// Chapter 10.2, 10.3, Appendix A.3, A.4

==== Timeouts
Chapter 7.3, Appendix A.1.3
