== Game Structure
=== Impartial Roles
To play an official match in the Small Size League, four impartial roles must be filled:

* the <<Referee, referee>>
* the <<Assistant Referee, assistant referee>>
* the <<Game Controller Operator, game controller operator>>
* the <<Vision Expert, vision expert>>

Usually, these roles are filled by two non-playing teams, with one team providing the <<Referee, referee>> and the <<Game Controller Operator, game controller operator>> and the other team providing the <<Assistant Referee, assistant referee>> and the <<Vision Expert, vision expert>>. The assignment of the roles is up to the <<Organizing Committee, organizing committee>>.

Every participating team is required to be able to provide enough people who are familiar with these roles.

==== Referee
Each match is controlled by the referee. He has full authority to enforce the rules of the Small Size League in connection with the match to which he has been appointed. The referee is encouraged to use the designated walking area next to the field (see <<Field Setup>>).

The referee is assisted by the <<Automatic Referee, automatic referee>> software. The human referee is allowed to override any decision made by the automatic referee software.

The decisions of the referee regarding facts connected with play are final. The referee may only change a decision on realizing that it is incorrect or, at his discretion, on the
advice of an assistant referee, provided that he has not restarted play.

The referee is not held liable for any kind of injury suffered by an official or spectator, any damage to property of any kind nor any other loss suffered by an individual, club, company, association, or other body.

The <<Robot Handler, robot handler>> is the only team member that may talk to the referee.

.Duties

* The referee ensures a safe match for all humans and robots
* The referee ensures a fair match according to the rules of the Small Size League
* The referee ensures that there is no interference by unauthorized persons or team members
* The referee or assistant referee places the ball for <<Kick-Off, kick-offs>> and <<Penalty Kick, penalties>> (division A) or after every <<Stopping The Game, stoppage>> (division B). Subsequently, the referee resumes the match
* The referee ensures that the game is started and resumed in time

==== Assistant Referee
The assistant referee supports the referee wherever he can. He is encouraged to use the designated walking area next to the <<Field Setup, field>>, opposite the referee.

No team members are allowed to talk to the assistant referee.

.Duties

* The assistant referee indicates when misconduct or any other incident has occurred out of the view of the referee
* The assistant referee discusses unclear situations with the referee
* The referee or assistant referee places the ball for <<Kick-Off, kick-offs>> and <<Penalty Kick, penalties>> (division A) or after every <<Stopping The Game, stoppage>> (division B)


==== Game Controller Operator
During a match, the game controller operator uses the <<Game Controller, game controller software>> as an interface between the <<Referee, referee>>, the <<Automatic Referee, automatic referee>> and the team software.

No team members are allowed to talk to the game controller operator, except the <<Robot Handler, robot handler>> for <<Robot Substitution, robot substitution>> intents.

.Duties
* The game controller operator configures the <<Game Controller, game controller>> before the game begins
* The game controller operator enters the signals of the <<Referee, referee>> into the <<Game Controller, game controller>>
* The game controller operator watches the game event log for any events that need attention, like detections of an <<Automatic Referee, automatic referee>> or elapsed timers and notifies the <<Referee, referee>>

==== Vision Expert
During a match, the vision expert is in charge of the <<Vision, shared vision system>> on the field.

Team members are generally advised not to talk to the vision expert, unless they experience major vision problems.

.Duties

* The vision expert checks the vision hardware and reports any kind of hardware problems to the <<Technical Committee, technical committee>>
* The vision expert monitors the shared vision system during the match and reports any kind of problems to the referee instantly
* The vision expert recalibrates the vision system if the referee deems it necessary

=== Team-Specific Roles

==== Robot Handler
Before the start of the match, every team has to designate one robot handler. The robot handler represents the team during the match.

.Duties
* The robot handler helps <<Match Preparation, preparing the match>>.
* The robot handler asks the referee for <<Timeouts, timeouts>> if necessary.
* The robot handler asks the referee for the permission to substitute a robot in the next stoppage and, if the referee agrees, <<Robot Substitution, substitutes the robot>>.
* The robot handler voices concerns of the team (for example network issues or vision problems).

=== Match Preparation
All people that fill a role in the match (<<Impartial Roles, impartial>> or <<Team-Specific Roles, team-specific>>) have to be ready at least 10 minutes before the start of the match to allow the referee to make the following preparations:

==== Game Result Sheet
The <<Referee, referee>> obtains a game result sheet from the <<Organizing Committee, organizing committee>>. After the game, the referee fills in the final score, collects the required signatures and submits the sheet to the <<Organizing Committee, organizing committee>>.

NOTE: While obtaining the game result sheet, the referee can also take an official <<Ball, ball>> and referee equipment such as a whistle or red and yellow cards (if provided).

==== Testing The Network
The <<Referee, referee>> ensures that both teams receive vision data and referee commands.

==== Choosing Team Colors
The <<Referee, referee>> asks the <<Robot Handler, robot handlers>> of the teams about their preferred team color (either blue or yellow). If the teams agree on a color assignment, the colors will be used for the entire match.

However, if both teams prefer the same color, the referee assigns the colors by chance. In this case, the teams switch the colors after the first half of the match as well as after the first half of the overtime if applicable.

==== Choosing Side And Kick-Off
The <<Referee, referee>> tosses a coin with both <<Robot Handler, robot handlers>>. The winning team chooses the goal it will attack in the first half of the match. The other team takes the <<Kick-Off, kick-off>> to start the match.

==== Choosing Keeper Id
The <<Referee, referee>> asks both <<Robot Handler, robot handlers>> which robot they will use as the keeper and forwards this information to the <<Game Controller Operator, game controller operator>>.

The keeper id can also be changed during game play. This can be done automatically by using the <<Game Controller, game controller>> network interface or by asking the <<Game Controller Operator, game controller operator>> to change it in the <<Game Controller, game controller>>. The <<Game Controller Operator, game controller operator>> must not change the keeper id until the ball is at a valid position.

Teams can automatically change their keeper id when the ball is on the opponent's half by using the <<Game Controller, game controller>> network interface.

NOTE: If a team does not want to use a keeper, it may select the id of a robot that is not on the field.

=== Game Stages
==== Overview
An official match of the Small Size League consists of the following stages:

|===
| Game Stage | Duration

| First Half | 300 seconds of playing time
| Half-Time Break | 300 seconds pause
| Second Half | 300 seconds of playing time
|===

If the match is an elimination match (draw is not a possible outcome) and the score is even after the regular game time, the match goes into overtime and the following game stages are added:

|===
| Game Stage | Duration

| Pre-Overtime Break | 300 seconds of pause
| Overtime First Half | 150 seconds of playing time
| Overtime Half-Time Break | 120 seconds of pause
| Overtime Second Half | 150 seconds of playing time
|===

If the score is even after overtime has been played, the following stages are added:

|===
| Game Stage | Duration

| Pre-Shoot-Out Break | 120 seconds of pause
| <<Shoot-Out>> | unlimited
|===

The match timer is paused whenever no team is allowed to <<Ball Manipulation, manipulate the ball>>. This includes <<Stop, stop>>, <<Halt, halt>> and the preparation states of <<Kick-Off, kick-off>> and <<Penalty Kick, penalty kick>>. Additionally, it is paused during <<Ball Placement, ball placement>>.

NOTE: As a result, the time needed for a match is much greater than the playing time.

==== Timeouts
The <<Robot Handler, robot handler>> has to ask the referee for a timeout. Timeouts are handled like <<Overview, breaks>>, meaning that both teams are allowed to make modifications to their software and hardware (see <<Autonomy>>).

Each team is allocated 4 timeouts at the beginning of the match. A total of 300 seconds is allowed for all timeouts. Timeouts may only be taken during a game
stoppage. The time is monitored and recorded by the <<Game Controller Operator, game controller operator>>.

NOTE: For example, a team may take 3 timeouts of 60 seconds duration and thereafter have only one timeout of up to 120 seconds duration.

During overtime, both teams can use 2 timeouts with a total time of 150 seconds. The number of timeouts and the time not used in regular game are not added.

No timeouts are possible in the <<Shoot-Out, shoot-out>> stage.

==== Early Termination At A Score Of 10
When a team manages to shoot 10 goals, the match is automatically terminated and the team with more goals is declared the winner, regardless of the current game stage.
