== 試合の構成/Game Structure
=== 公正な役割/Impartial Roles
小型機リーグの公式な試合を行うためには、4人の公平な役割を揃えなければならない。 +
To play an official match in the Small Size League, four impartial roles must be filled:

* <<主審/Referee>>
* <<副審/Assistant Referee>>
* <<Game Controller Operator>>
* <<Vision Expert>>

通常、これらの役割は、試合に出場していない2チームによって行われる。1チーム目は<<主審/Referee, 主審>>と<<Game Controller Operator, game controller operator>> を、2チーム目は<<副審/Assistant Referee, 副審>>と<<Vision Expert, vision expert>>を担当する。これらの役割は<<組織委員会/Organizing Committee, 組織委員会>>によって割り当てられる。 +
Usually, these roles are filled by two non-playing teams, with one team providing the <<主審/Referee, referee>> and the <<Game Controller Operator, game controller operator>> and the other team providing the <<副審/Assistant Referee, assistant referee>> and the <<Vision Expert, vision expert>>. The assignment of the roles is up to the <<組織委員会/Organizing Committee, organizing committee>>.

すべての参加するチームはこれらの役割に精通した十分な人材を提供できることが求められる。 +
Every participating team is required to be able to provide enough people who are familiar with these roles.

==== 主審/Referee
各試合は主審によってコントロールされる。主審は任命された試合に関して競技規則を施行する一切の権限を持つ。主審はフィールド横にある歩行エリアを使うことが推奨される(「<<フィールドセットアップ/Field Setup,フィールドセットアップ>>」を参照)。 +
Each match is controlled by the referee. He has full authority to enforce the rules of the Small Size League in connection with the match to which he has been appointed. The referee is encouraged to use the designated walking area next to the field (see <<フィールドセットアップ/Field Setup, Field Setup>>).

主審は<<オートレフ/Automatic Referee, オートレフ>>による補助を受ける。人間の主審は、オートレフによる決定がどのような物であってもこれを上書きすることが許可されている。 +
The referee is assisted by the <<オートレフ/Automatic Referee, automatic referee>> software. The human referee is allowed to override any decision made by the automatic referee software.

プレイに関する事実についての主審の決定は、最終的なものである。プレイを再開する前、または試合を終結する前であれば、主審は、その直前の決定が正しくないことに気づいたとき、または主審の裁量によって副審の助言を採用したときのみ、決定を変えることができる。 +
The decisions of the referee regarding facts connected with play are final. The referee may only change a decision on realizing that it is incorrect or, at his discretion, on the
advice of an assistant referee, provided that he has not restarted play.

ルールはすべての状況に対してその結果を詳細に定義するものではない。
したがって主審は、ルールが明確でないときは適切な方法で判断を下すことが推奨される。
よくある手順として、「<<非スポーツマン行為/Unsporting Behavior, 非スポーツマン行為>>」があった場合はまずは警告を発し、繰り返された場合は罰則を適用する、というものがある。 +
The rules do not define all circumstance and their consequences in every detail.
The referee is thus advised to judge in an adequate way, if the rules are not explicit.
The usual procedure is to issue a warning on the first occurrence and an <<非スポーツマン行為/Unsporting Behavior, Unsporting Behavior>> on repetition.

主審は、役員または観客のあらゆる怪我、あらゆる種類の財産への損害、個人、クラブ、会社、協会、またはその他の団体に対するその他の損失に対し、法的な責任を負わない。 +
The referee is not held liable for any kind of injury suffered by an official or spectator, any damage to property of any kind nor any other loss suffered by an individual, club, company, association, or other body.

<<ハンドラー/Robot Handler, ハンドラー>>は主審と話すことができる唯一のチームメンバーである。 +
The <<ハンドラー/Robot Handler, robot handler>> is the only team member that may talk to the referee.

.職務/Duties

* 主審はすべての人間とロボットが安全に試合をできることを保証する +
The referee ensures a safe match for all humans and robots
* 主審は小型機リーグのルールに則った公平な試合を保証する +
The referee ensures a fair match according to the rules of the Small Size League
* 主審は許可されていない人間やチームメンバーによる干渉が発生していないことを保証する +
The referee ensures that there is no interference by unauthorized persons or team members
* 主審か副審は<<キックオフ/Kick-Off, キックオフ>>や<<ペナルティーキック/Penalty Kick, ペナルティーキック>> (ディヴィジョンA)もしくは<<試合の停止/Stopping The Game,試合の停止>>(ディヴィジョンB)の時にボールを配置する。その後、主審は試合を再開する。 +
The referee or assistant referee places the ball for <<キックオフ/Kick-Off, kick-offs>> and <<ペナルティーキック/Penalty Kick, penalties>> (division A) or after every <<試合の停止/Stopping The Game, stoppage>> (division B). Subsequently, the referee resumes the match
* 主審は時間内に試合が開始もしくは再開されることを保証する +
The referee ensures that the game is started and resumed in time

==== 副審/Assistant Referee
副審はどこでも可能な限り主審の補助をする。副審は主審と反対側の<<フィールドセットアップ/Field Setup, フィールド>>横にある歩行エリアを使うことが推奨される。 +
The assistant referee supports the referee wherever he can. He is encouraged to use the designated walking area next to the <<フィールドセットアップ/Field Setup, field>>, opposite the referee.

いかなるチームメンバーも副審と会話することは許可されない。 +
No team members are allowed to talk to the assistant referee.

.職務/Duties

* 副審は主審に見えなかった不正行為やその他の出来事が起きたとき合図をする +
The assistant referee indicates when misconduct or any other incident has occurred out of the view of the referee
* 副審は主審と不明確な状況について議論をする +
The assistant referee discusses unclear situations with the referee
* 主審か副審はキックオフやペナルティーキック(ディヴィジョンA)もしくは試合の停止(ディヴィジョンB)の時にボールを配置する。 +
The referee or assistant referee places the ball for <<キックオフ/Kick-Off, kick-offs>> and <<ペナルティーキック/Penalty Kick, penalties>> (division A) or after every <<試合の停止/Stopping The Game, stoppage>> (division B)


==== Game Controller Operator
競技中、game controller operatorは<<主審/Referee, 主審>>、<<オートレフ/Automatic Referee, オートレフ>>と各チームのソフトウェアの間のインターフェースとなる<<Game Controller, game controller software>>を使用する。 +
During a match, the game controller operator uses the <<Game Controller, game controller software>> as an interface between the <<主審/Referee, referee>>, the <<オートレフ/Automatic Referee, automatic referee>> and the team software.

<<ハンドラー/Robot Handler, ハンドラー>>が<<ロボットの交代/Robot Substitution, ロボットの交代>>をする時を除いて、いかなるチームメンバーもgame controller operatorと会話することは許可されない。 +
No team members are allowed to talk to the game controller operator, except the <<ハンドラー/Robot Handler, robot handler>> for <<ロボットの交代/Robot Substitution, robot substitution>> intents.

.職務/Duties
* game controller operatorは<<Game Controller, game controller>>を試合前に設定する +
The game controller operator configures the <<Game Controller, game controller>> before the game begins
* game controller operatorは<<主審/Referee, 主審>>からの合図を<<Game Controller, game controller>>に入力する +
The game controller operator enters the signals of the <<主審/Referee, referee>> into the <<Game Controller, game controller>>
* game controller operatorは注意を必要とするあらゆるゲームイベントログ(<<オートレフ/Automatic Referee, オートレフ>>による検出や試合の経過時間など)を監視し、<<主審/Referee, 主審>>に通知する +
The game controller operator watches the game event log for any events that need attention, like detections of an <<オートレフ/Automatic Referee, automatic referee>> or elapsed timers and notifies the <<主審/Referee, referee>>

NOTE: (訳者注記)日本では一般的に「レフボ」と呼称されることが多い。これは、同様の機能を持った旧世代のソフトウェアである「ssl-refbox」、およびその操作担当である「refbox operator」(2018年の大会をもって廃止)に由来する。

==== Vision Expert
競技中、Vision Expertはフィールドの<<Vision, 共有Visionシステム>>を担当する。 +
During a match, the vision expert is in charge of the <<Vision, shared vision system>> on the field.

Visionに大きな問題が発生した場合を除いて、チームメンバーは一般的にVision Expertに対して話しかけない事を推奨する。 +
Team members are generally advised not to talk to the vision expert, unless they experience major vision problems.

.職務/Duties

* Vision expertはVisionのハードウェアをチェックし、あらゆる種類のハードウェアの問題を<<技術委員会/Technical Committee, 技術委員会>>に報告する。 +
The vision expert checks the vision hardware and reports any kind of hardware problems to the <<技術委員会/Technical Committee, technical committee>>
* Vision expertは試合中に共有Visionシステムを監視し、あらゆる種類の問題を主審に即座に報告する。 +
The vision expert monitors the shared vision system during the match and reports any kind of problems to the referee instantly
* 主審が必要であると考えた場合には、Vision expertはVision systemを再キャリブレーションする。 +
The vision expert recalibrates the vision system if the referee deems it necessary

NOTE: (訳者注記)日本では一般的に「ビジョン」と呼称されることが多い。Visionソフトウェアそのものと混同される懸念があるが、Vision Expertが呼ばれるということはVisionソフトウェアに異常がある場合が大半であり、運用する上で支障があることはあまりない。

=== チーム固有の役割/Team-Specific Roles

==== ハンドラー/Robot Handler
試合開始前に、すべてのチームは1人のハンドラーを指定しなければならない。ハンドラーは試合中にチームを代表する。 +
Before the start of the match, every team has to designate one robot handler. The robot handler represents the team during the match.

.職務/Duties
* ハンドラーは<<競技の準備/Match Preparation, 競技の準備>>の補助を行う。 +
The robot handler helps <<競技の準備/Match Preparation, preparing the match>>.
* 必要であれば、ハンドラーは主審に<<タイムアウト/Timeouts, タイムアウト>>を要求する。 +
The robot handler asks the referee for <<タイムアウト/Timeouts, timeouts>> if necessary.
* ハンドラーは<<ロボットの交代/Robot Substitution, 試合中にロボットを交代することができる>>。 +
The robot handler can <<ロボットの交代/Robot Substitution, substitute a robot during game play>>.
* ハンドラーは次のStop Game時にロボットを交代する許可を主審に要求し、主審が許可した場合は<<ロボットの交代/Robot Substitution,ロボットを交代する>>。 +
The robot handler asks the referee for the permission to substitute a robot in the next stoppage and, if the referee agrees, <<ロボットの交代/Robot Substitution, substitutes the robot>>.
* ハンドラーはチームの懸念事項を表明する(例えばネットワークやビジョンの問題)。 +
The robot handler voices concerns of the team (for example network issues or vision problems).

=== 競技の準備/Match Preparation
競技で役割のあるすべての人間(「<<公正な役割/Impartial Roles, 公平な役割>>」もしくは「<<チーム固有の役割/Team-Specific Roles, チーム固有の役割>>」を参照)は、以下に述べる主審による競技の準備を可能にするために、少なくとも試合開始の10分前には準備できていなければならない: +
All people that fill a role in the match (<<公正な役割/Impartial Roles, impartial>> or <<チーム固有の役割/Team-Specific Roles, team-specific>>) have to be ready at least 10 minutes before the start of the match to allow the referee to make the following preparations:

==== 試合結果シート/Game Result Sheet
<<主審/Referee, 主審>>は<<組織委員会/Organizing Committee, 組織委員会>>から試合結果シートを受け取る。試合後に、主審は最終結果を記入し、必要な署名を集めてシートを<<組織委員会/Organizing Committee, 組織委員会>>に提出する。 +
The <<主審/Referee, referee>> obtains a game result sheet from the <<組織委員会/Organizing Committee, organizing committee>>. After the game, the referee fills in the final score, collects the required signatures and submits the sheet to the <<組織委員会/Organizing Committee, organizing committee>>.

NOTE: 試合結果シートを受け取っている間、主審は<<ボール/Ball, 公式球>>と(もし提供されるのであれば)ホイッスルやレッドカードイエローカードなどの審判向けの機器も使用できる。 +
While obtaining the game result sheet, the referee can also take an official <<ボール/Ball, ball>> and referee equipment such as a whistle or red and yellow cards (if provided).

==== ネットワークのテスト/Testing The Network
<<主審/Referee, 主審>>は両方のチームがVisionデータとレフェリーコマンドを受信できるか確認する。 +
The <<主審/Referee, referee>> ensures that both teams receive vision data and referee commands.

==== チームカラーの選択/Choosing Team Colors
<<主審/Referee, 主審>>は両チームの<<ハンドラー/Robot Handler, ハンドラー>>に希望するチームカラー(青か黄色のどちらか)を確認する。両チームが色の割り当てに同意するのであれば、その試合を通してその色が使用される。 +
The <<主審/Referee, referee>> asks the <<ハンドラー/Robot Handler, robot handlers>> of the teams about their preferred team color (either blue or yellow). If the teams agree on a color assignment, the colors will be used for the entire match.

ただし、両チームが同じ色を希望した場合は、主審は色を任意に割り当てる。この場合、可能であれば、両チームは前半終了後と延長戦の前半終了後に色を入れ替える。 +
However, if both teams prefer the same color, the referee assigns the colors by chance. In this case, the teams switch the colors after the first half of the match as well as after the first half of the overtime if applicable.

==== ロボット外装色の選択/Choosing Robot Hull Colors
チームは試合前に<<ロボットの色/Color of Robots, ロボット外装の色>> (暗もしくは明)を選択してよい。両チームが同じ色を選択した場合、<<主審/Referee, 主審>>は試合開始前に任意に色を割り当てる。選択された外装色は試合を通して使用されなければならない。 +
Teams are encouraged to choose their preferred <<Color of Robots, robot hull color>> (dark or bright) before the match. If both teams choose the same color, the <<Referee, referee>> assigns the colors by chance before the game starts. The selected hull color must be used throughout the game.

==== 陣地とキックオフの選択/Choosing Side And Kick-Off
<<主審/Referee, 主審>>は両チームの<<ハンドラー/Robot Handler, ハンドラー>>と一緒にコイントスを行う。コイントスの勝者が前半戦で攻めるゴールを選ぶ。もう一方のチームが前半戦開始時の<<キックオフ/Kick-Off, キックオフ>>を行う。 +
The <<主審/Referee, referee>> tosses a coin with both <<ハンドラー/Robot Handler, robot handlers>>. The winning team chooses the goal it will attack in the first half of the match. The other team takes the <<キックオフ/Kick-Off, kick-off>> to start the match.

==== ゴールキーパーのIDの選択/Choosing Keeper Id
<<主審/Referee, 主審>>は両チームの<<ハンドラー/Robot Handler, ハンドラー>>にどのロボットをキーパーとして使用するつもりなのか確認し、<<Game Controller Operator, game controller operator>>に情報を連絡する。 +
The <<主審/Referee, referee>> asks both <<ハンドラー/Robot Handler, robot handlers>> which robot they will use as the keeper and forwards this information to the <<Game Controller Operator, game controller operator>>.

キーパーのIDは、<<インプレイとアウトオブプレイ/Ball In And Out Of Play, アウトオブプレイ中>>もしくはボールがフィールドの相手側ハーフにあれば、以下の方法でいつでも変更できる: +
The keeper id can be changed anytime during the game if the ball is either <<インプレイとアウトオブプレイ/Ball In And Out Of Play, out of play>> or in the opponent's field half by:

. <<Game Controller, Game controller>>のネットワークインターフェースを利用する +
Using the <<Game Controller, game controller>> network interface
. <<Game Controller Operator, game controller operator>>に、<<Game Controller, game controller>>で設定されているキーパーのIDを変更するよう依頼する。<<Game Controller Operator, Game controller operator>>は、ボールが適切な位置に来るまでキーパーのIDを変更してはならない。 +
Asking the <<Game Controller Operator, game controller operator>> to change it in the <<Game Controller, game controller>>. The <<Game Controller Operator, game controller operator>> must not change the keeper id until the ball is at a valid position.

NOTE: チームは、要件を満たした時にのみ変更を要請する必要がある。<<Game Controller Operator, Game controller operator>>はルールを尊守する必要がある。 +
Teams should only ask for a change once the requirements are met. The <<Game Controller Operator, game controller operator>> is responsible for complying to the rules.

NOTE: もしチームがキーパーを使用したくない場合、フィールド上に存在しないロボットのIDを選択すること。 +
If a team does not want to use a keeper, it may select the id of a robot that is not on the field.

=== ゲームステージ/Game Stages
==== 概要/Overview
小型機リーグの公式戦は以下に示すステージによって構成される。 +
An official match of the Small Size League consists of the following stages:

|===
| Game Stage | 期間/Duration

| 前半戦 +
First Half
| 300秒の競技時間 +
300 seconds of playing time
| ハーフタイム +
Half-Time Break
| 300秒の休憩 +
300 seconds pause
| 後半戦 +
Second Half
| 300秒の競技時間 +
300 seconds of playing time
|===

試合が勝ち抜き方式(引き分けが有効な結果とされない状態)かつ規定の試合時間経過後に同点の場合、競技は延長戦に進み次のゲームステージが追加される： +
If the match is an elimination match (draw is not a possible outcome) and the score is even after the regular game time, the match goes into overtime and the following game stages are added:

|===
| ゲームステージ / Game Stage | 期間 / Duration

| 延長戦前の休憩 +
Pre-Overtime Break
| 300秒の休憩 +
300 seconds of pause

| 延長前半戦 +
Overtime First Half
| 150秒の競技時間 +
150 seconds of playing time

| 延長戦ハーフタイム +
Overtime Half-Time Break
| 120秒の休憩 +
120 seconds of pause

| 延長後半戦 +
Overtime Second Half
| 競技時間は150秒 +
150 seconds of playing time

|===

延長戦終了時点で同点の場合、以下のステージを追加する: +
If the score is even after overtime has been played, the following stages are added:

|===
| ゲームステージ / Game Stage | 期間 / Duration

| シュートアウトの準備 +
Pre-Shoot-Out Break
| 120秒の休憩 +
120 seconds of pause

| <<シュートアウト/Shoot-Out, シュートアウト>> +
<<シュートアウト/Shoot-Out, Shoot-Out>>
| 無制限 +
unlimited

|===

競技のタイマーは両チームとも<<ボールの操作/Ball Manipulation,ボールを操作する>>ことが許されない場合に一時停止される。これには<<停止/Stop, ストップゲーム>>、<<ハルト/Halt, ハルト>>、<<キックオフ/Kick-Off, キックオフ>>と<<ペナルティーキック/Penalty Kick,ペナルティーキック>>の準備時間が含まれる。さらに<<ボール配置/Ball Placement, ボール配置中>>もタイマーは一時停止される。 +
The match timer is paused whenever no team is allowed to <<ボールの操作/Ball Manipulation, manipulate the ball>>. This includes <<停止/Stop, stop>>, <<ハルト/Halt, halt>> and the preparation states of <<キックオフ/Kick-Off, kick-off>> and <<ペナルティーキック/Penalty Kick, penalty kick>>. Additionally, it is paused during <<ボール配置/Ball Placement, ball placement>>.

NOTE: この結果、試合に必要な時間は競技時間よりもはるかに長くなる。 +
As a result, the time needed for a match is much greater than the playing time.

==== タイムアウト/Timeouts
タイムアウトを取りたい時、<<ハンドラー/Robot Handler, ハンドラー>>は主審に確認をとらなければならない。タイムアウトは<<概要/Overview, 休憩>>のように扱われ、両チームとも自らのソフトウェアとハードウェアの修正を行うことが許可されている(「<<自律性/Autonomy, 自律性>>」を参照)。 +
The <<ハンドラー/Robot Handler, robot handler>> has to ask the referee for a timeout. Timeouts are handled like <<概要/Overview, breaks>>, meaning that both teams are allowed to make modifications to their software and hardware (see <<自律性/Autonomy,Autonomy>>).

タイムアウト中に物理的な接触があったロボットは、フィールド外に除去されなければならない。これは除去したものと同一のタイムアウト中であっても、「<<ロボットの交代/Robot Substitution, ロボットの交代>>」に記載されたエリアからフィールド内に投入することができる。 +
Any robot that has been physically interacted with during a timeout must be taken out of the field. It can be brought in again, also during the same timeout, via the area outlined in <<ロボットの交代/Robot Substitution, Robot Substitution>>.

どちらのチームも競技開始から4回までのタイムアウトが割り当てられている。すべてのタイムアウトの合計は300秒まで許されている。タイムアウトはstop game中のみ取得することができる。時間は<<Game Controller Operator, game controller operator>>によって監視と記録がされている。 +
Each team is allocated 4 timeouts at the beginning of the match. A total of 300 seconds is allowed for all timeouts. Timeouts may only be taken during a game
stoppage. The time is monitored and recorded by the <<Game Controller Operator, game controller operator>>.

NOTE: 例えば、1チームが60秒間のタイムアウトを3回取得していたら、残りはあと120秒間で1回のタイムアウトしか取得できない。 +
For example, a team may take 3 timeouts of 60 seconds duration and thereafter have only one timeout of up to 120 seconds duration.

延長戦の間は、両チームとも合計150秒間で2回のタイムアウトを取得できる。レギュラーゲームで使われなかったタイムアウトの回数と時間は加算されない。 +
During overtime, both teams can use 2 timeouts with a total time of 150 seconds. The number of timeouts and the time not used in regular game are not added.

<<シュートアウト/Shoot-Out, シュートアウト>>の間はタイムアウトを取得できない。 +
No timeouts are possible in the <<シュートアウト/Shoot-Out, shoot-out>> stage.

==== 10点先取による早期終了/Early Termination At A Score Of 10
<<シュートアウト/Shoot-Out, シュートアウト>>までのゲームステージでは、片方のチームが10点目のゴールを決めたとき、
得点差が1点より大きければ試合は自動的に終了され、得点数の多い方が勝者となる。 +
Before the <<シュートアウト/Shoot-Out, shoot-out>> stage, when a team manages to shoot 10 goals,
the match is automatically terminated as soon as the goal difference is greater than one and
the team with more goals is declared the winner.

NOTE: 予選段階では勝利数が均衡状態にあるときには得点されたゴールの数で順位付けを行うため、ゴールの絶対数は全体的なスコアリングにとって重要である。
単純化するため、このルールは全ての試合に適用される。 +
During the group phase, the number of goals scored is used as tie-breaker, so the absolute number of goals matter for overall scoring.
The rule applies to all game types for simplicity.
