== Game Structure
NOTE: References to the male gender in the rules with respect to referees, team members, officials, etc. are for simplification and apply to both males and females.

=== Impartial Roles
To play an official match in the Small Size League, four impartial roles must be filled:

* the <<Referee, referee>>
* the <<Assistant Referee, assistant referee>>
* the <<Game Controller Operator, game controller operator>>
* the <<Vision Exptert, vision expert>>

Usually, these roles are filled by two non-playing teams, with one team providing the <<Referee, referee>> and the <<Game Controller Operator, game controller operator>> and the other team providing the <<Assistant Referee, assistant referee>> and the <<Vision Exptert, vision expert>>. The assignment of the roles is up to the organizing committee.

Every participating team is required to be able to provide enough people who are familiar with these roles.

==== Referee
Each match is controlled by the referee. He has full authority to enforce the rules of the Small Size League in connection with the match to which he has been appointed. The referee is encouraged to use the designated walking area next to the field (see <<Field Setup>>).

The referee is assisted by the <<Automatic Referee, automatic referee>> software. The human referee is allowed to override any decision made by the automatic referee software.

The decisions of the referee regarding facts connected with play are final. The referee may only change a decision on realising that it is incorrect or, at his discretion, on the
advice of an assistant referee, provided that he has not restarted play.

The referee is not held liable for any kind of injury suffered by an official or spectator, any damage to property of any kind nor any other loss suffered by an individual, club, company, association, or other body.

.Duties

* The referee ensures a safe match for all humans and robots
* The referee ensures a fair match according to the rules of the Small Size League
* The referee ensures that there is no interference by unauthorized persons or team members

==== Assistant Referee
The assistant referee supports the referee whereever he can. He is encouraged to use the designated walking area next to the field (see <<Field Setup>>), opposite the referee.

.Duties

* The assistant referee indicates when misconduct or any other incident has occurred out of the view of the referee
* The assistant referee discusses unclear situations with the referee


==== Game Controller Operator
Chapter 6.1

==== Vision Exptert
Appendix B.1

=== Team-Specific Roles
==== Robot Handler
Chapter 3 Decision 1

=== Game preparation
Chapter 4 Decision 6

==== Game Result Sheet
==== Choosing Colors, Side And Kick-Off
Chapter 4.5, 8.1

=== Game Stages
==== Overview
Chapter 7.1, Appendix A.1
// Chapter 10.2, 10.3, Appendix A.3, A.4

==== Timeouts
Chapter 7.3, Appendix A.1.3
