== Offenses
=== No Progress In Game
If there is no progress in the game for 5 seconds (Division A) or 10 seconds (Division B) while both teams are allowed to
<<Ball Manipulation, manipulate the ball>>, the game is <<Stop, stopped>>
and continued by a <<Force Start, forced start>>.

=== Double Touch
When the ball is brought <<Ball In And Out Of Play, into play>> following a <<Kick-Off, kick-off>> or <<Free Kick, free kick>>,
the kicker is not allowed to touch the ball until it has been touched by another robot or the game has been stopped.

The ball must have moved at least 0.05 meters to be considered as <<Ball In And Out Of Play, in play>>.

A double touch results in a <<Stop, stop>> followed by a <<Free Kick, free kick>> from the same ball position.

NOTE: It is understood that the ball may be bumped by the robot multiple times over a short distance while the kick is being taken.
This is why a distance of 0.05 meters is used to decide whether a robot violates this rule or not.
Remaining in contact with the ball for more than 0.05 meters also counts as double touch, even though technically the robot only touched the ball once.

=== Unsporting Behavior
Unsporting behavior can lead to <<Yellow Card, yellow cards>>, <<Red Card, red cards>>, <<Penalty Kick, penalty kicks>>, a <<Forced Forfeit, forced forfeit>> or a <<Disqualification, disqualification>>. The human <<Referee, referee>> chooses an appropriate sanction, depending on the severity of the offense.

NOTE: If the referee is not sure which sanction to choose, he may confer with members of the <<Technical Committee, technical committee>> or the <<Organizing Committee, organizing committee>>.

Some examples of unsporting behavior are listed below.

==== Damaging Other Robots
It is not allowed to damage or modify robots of other teams.

==== Damaging The Field Or The Ball
It is not allowed to damage or modify the field or the ball.

==== Showing Lack Of Respect
A team member must show appropriate respect to everyone involved in the game. Infringements of this rule include but are not limited to:

* insulting the opponent, the <<Referee, referee>> or other persons holding an <<Impartial Roles, impartial role>>
* annoying the <<Referee, referee>> or other persons holding an <<Impartial Roles, impartial role>>
* not obeying the orders of the <<Referee, referee>>



=== Fouls
The number of fouls per team is tracked by a counter. Each foul will
increase the counter by one. Every third increase to the foul counter
causes a <<Yellow Card, yellow card>> to be awarded.

Violations in this section and its subsections increase the foul counter if not stated otherwise.

NOTE: Regardless, of the prescribed penalties in this section, if a
foul is severe or repeated, the referee can choose to immediately
issue a <<Yellow Card, yellow card>> or in extreme cases a <<Red Card,
red card>>.



==== Stopping Fouls
Fouls in this section cause the game to <<Stop, stop>> and then resume
with a <<Free Kick, free kick>> from the position where the ball was
located when the foul began happening.

===== Robot Too Close To Opponent Defense Area
During <<Stop, stop>> and <<Free Kick, free kicks>>, before the ball <<Resuming The Game, has entered play>>, all robots have to keep at least 0.2 meters distance to the opponent <<Defense Area, defense area>>.

There is a grace period of 2 seconds for the robots to move away from the opponent defense area.

===== Pushing
A robot pushes an opponent robot if both robots keep contact to the ball or to each other while the robot exerts force onto the opponent robot, such that both robots travel towards the opponent robot.

NOTE: If both robots are pushing each other with similar force, no team is at fault.

===== Ball Holding
Robots must not surround the ball to prevent access by others.

===== Tipping Over Or Dropping Parts
A robot must not tip over, break or drop parts on the field that pose a potential threat to other robots.

A robot violating this rule has to be <<Robot Substitution, substituted>>.

NOTE: Metal parts (screws for example) as well as larger parts generally pose a potential threat, very small non-metal parts (for example rubber subwheel rings) don't.

===== Multiple Defenders
NOTE: This rule does not use the standard sanctions defined for <<Fouls, fouls>>.

Robots other than the keeper must maintain best-effort to fully stay outside the own defense area.
Infraction of this rule can be rated as unsporting behavior.

If a robot other than the keeper touches the ball while this robot is entirely
inside its own defense area, the game is stopped and a <<Penalty Kick,
penalty kick>> is awarded to the other team. The foul counter is *not*
increased.

===== Boundary Crossing
A robot must not kick the ball over the field boundary such that the ball leaves the field.

===== Keeper Held Ball
The ball must not be kept in the <<Defense Area, defense area>> for more than
5 seconds (Division A) or 10 seconds (Division B).

===== Excessive Dribbling
A robot must not <<Dribbling Device, dribble>> the ball further than 1 meter, measured linearly from the ball location where the dribbling started. A robot begins dribbling when it makes contact with the ball and stops dribbling when there is an observable separation between the ball and the robot.

NOTE: Dribblers can still be used to dribble large distances with the ball as long as the robot periodically loses possession, such as kicking the ball ahead of it as human soccer players often do.



==== Non Stopping Fouls
Fouls in this section do not cause a <<Stop, stop>>.
Instead, the game continues normally.

The same no stop foul cannot be triggered again until the foul
condition has stopped being violated or there has been 2 seconds since
the foul was first triggered. This is to allow teams to adjust their
robots' positions, ball speed or any other property that is causing
the violation before being penalized additional times.

===== Attacker Touched Ball In Opponent Defense Area
The ball must not be touched by a robot, while the robot is partially or fully inside the opponent <<Defense Area, defense area>>.

===== Ball Speed
A robot must not accelerate the ball faster than 6.5 meters per second in 3D space.

===== Crashing
At the moment of collision of two robots of different teams, the difference of the speed vectors of both robots is taken and projected onto the line that is defined by the position of both robots. If the length of this projection is greater than 1.5 meters per second, the faster robot committed a foul. If the absolute robot speed difference is less than 0.3 meters per second, both conduct a foul.



==== Fouls While Ball Out Of Play
Fouls in this section can only occur when the ball is <<Ball In And Out Of Play, out of play>>.

Each foul has a grace period of 2 seconds per team until it is raised again.

NOTE: If multiple robots commit the same foul within 2 seconds, only the first foul counts.

NOTE: If a robot keeps committing a foul, it will be punished again after the grace period.

===== Defender Too Close To Ball
A robot's distance to the ball must be at least 0.5 meters during an opponent <<Kick-Off, kick-off>> or <<Free Kick, free kick>>.
When the foul is committed, the timer of the opponent team for bringing the ball into play is reset.

The <<Referee, human referee>> may decide to repeat the <<Kick-Off, kick-off>> or <<Free Kick, free kick>> on significant disturbances.

NOTE: During <<Stop, stop>>, there is no automatic sanction for being too close to the ball. The referee may still punish a team for <<Unsporting Behavior,unsporting behavior>> by issuing a <<Yellow Card, yellow card>> if it does not respect the required distance. See <<Stop, stop>> for further explanation.

===== Robot Stop Speed
A robot must not move faster than 1.5 meters per second during <<Stop, stop>>. A violation of this rule is only counted once per robot and stoppage.

There is a grace period of 2 seconds for the robots to slow down.

NOTE: This rule does not apply to <<Ball Placement, ball placement>>.

NOTE: Since the stop command is used for manual ball placement and
<<Robot Substitution, robot substitution>>, the intention of the robot
speed limit is to avoid robots harming the people on the field.

===== Ball Placement Interference
During <<Ball Placement, ball placement>>, all robots of the non-placing team have to keep at least 0.5 meters distance to the line between the ball and the placement position (the forbidden area forms a stadium shape).

If a robot of the non-placing team is too close to the line between
the ball and the placement position for more than 2 seconds, it
commits a foul. In this case, 10 seconds are added to the ball
placement timer.
Only one interference foul per ball placement phase counts towards the foul counter, but the placement timer is always incremented.

NOTE: This rule does not cover all cases of ball placement interference.
The <<Referee, referee>> is encouraged to call fouls if the non-placing team is obviously interfering with the ball placement.

NOTE: If a robot keeps interfering the ball placement (for example if it is stuck or can not move), the human referee is encouraged to stop the placement and place the ball manually.
