== 反則/Offenses
=== 試合の停滞/No Progress In Game
両チームが<<ボールの操作/Ball Manipulation, ボールを操作する>>ことが許されているにもかかわらず5秒 (ディヴィジョンA)もしくは10秒 (ディヴィジョンB)に亘って試合に進展がなかった場合、試合は<<停止/Stop, 停止され>>、<<フォーススタート/Force Start, フォーススタート>>で再開される。 +
If there is no progress in the game for 5 seconds (Division A) or 10 seconds (Division B) while both teams are allowed to
<<ボールの操作/Ball Manipulation, manipulate the ball>>, the game is <<停止/Stop, stopped>>
and continued by a <<フォーススタート/Force Start, forced start>>.

=== ダブルタッチ/Double Touch

<<キックオフ/Kick-Off, キックオフ>>、<<フリーキック/Free Kick, フリーキック>>、<<ペナルティーキック/Penalty Kick, ペナルティーキック>>によってボールがインプレイに持ち込まれたとき、キッカーは他のロボットが触れるか、試合が停止するまでボールに触れてはならない。 +
When the ball is brought <<インプレイとアウトオブプレイ/Ball In And Out Of Play, into play>> following a <<キックオフ/Kick-Off, kick-off>> or <<フリーキック/Free Kick, free kick>>, the kicker is not allowed to touch the ball until it has been touched by another robot or the game has been stopped.

<<インプレイとアウトオブプレイ/Ball In And Out Of Play, インプレイ>>になったとみなされるには、少なくとも0.05m以上ボールが動いていなければならない。 +
The ball must have moved at least 0.05 meters to be considered as <<インプレイとアウトオブプレイ/Ball In And Out Of Play, in play>>.

ダブルタッチによって試合は<<停止/Stop, 停止>>され、次いで同じボールの位置から<<フリーキック/Free Kick, フリーキック>>となる。 +
A double touch results in a <<停止/Stop, stop>> followed by a <<フリーキック/Free Kick, free kick>> from the same ball position.

NOTE: キックが行われている間に、ロボットにぶつかったボールが短い距離で何度もはねるであろうことは理解されている。
そこで、ロボットがルールに違反しているかどうかの判定に0.05mの距離が使用される。
技術的にロボットが一度しかボールに触れていなかったとしても、0.05m以上ボールと接触し続けた場合は、ダブルタッチとみなされる。 +
It is understood that the ball may be bumped by the robot multiple times over a short distance while the kick is being taken.
This is why a distance of 0.05 meters is used to decide whether a robot violates this rule or not.
Remaining in contact with the ball for more than 0.05 meters also counts as double touch, even though technically the robot only touched the ball once.

=== 非スポーツマン行為/Unsporting Behavior
非スポーツマン行為は<<イエローカード/Yellow Card, イエローカード>>、<<レッドカード/Red Card, レッドカード>>、<<ペナルティーキック/Penalty Kick, ペナルティーキック>>、<<強制的な試合放棄/Forced Forfeit, 強制的な試合放棄>>、<<失格/Disqualification, 失格>>につながる可能性がある。人間の<<主審/Referee, 主審>>は反則の重大さに応じて適切な処罰を選択する。 +
Unsporting behavior can lead to <<イエローカード/Yellow Card, yellow cards>>, <<レッドカード/Red Card, red cards>>, <<ペナルティーキック/Penalty Kick, penalty kicks>>, a <<強制的な試合放棄/Forced Forfeit, forced forfeit>> or a <<失格/Disqualification, disqualification>>. The human <<主審/Referee, referee>> chooses an appropriate sanction, depending on the severity of the offense.

軽微なものであれば<<イエローカード/Yellow Card, イエローカード>>の適用で十分であるが、
それにより当該チームが優位になるようなものであれば、<<レッドカード/Red Card, レッドカード>>や<<ペナルティーキック/Penalty Kick, ペナルティーキック>>が与えられる。 +
For minor infringements, a <<イエローカード/Yellow Card, イエローカード>> is adequate,
while on more severe infringements, that gave the team an advantage, a <<レッドカード/Red Card, Red Card>> or <<ペナルティーキック/Penalty Kick, Penalty Kick>> can be issued.

より厳しい制裁を与える場合は、主審は<<技術委員会/Technical Committee, 技術委員会>>や<<組織委員会/Organizing Committee, 組織委員会>>に相談することを推奨する。
For harder sanctions, the referee is advised to refer to members of the <<技術委員会/Technical Committee, technical committee>> or the <<組織委員会/Organizing Committee, organizing committee>>.

NOTE: 審判は、どの処罰を選択すべきか判断できない場合は、<<副審/Assistant Referee, 副審>>や<<技術委員会/Technical Committee, 技術委員会>>または<<組織委員会/Organizing Committee, 組織委員会>>のメンバーと協議することができる。 +
If the referee is not sure which sanction to choose, he may confer with the <<副審/Assistant Referee, assistant referee>> and members of the <<技術委員会/Technical Committee, technical committee>> or the <<組織委員会/Organizing Committee, organizing committee>>.

非スポーツマン行為のいくつかの例は以下の通りである。 +
Some examples of unsporting behavior are listed below.

==== 他ロボットへの傷害/Damaging Other Robots
他のチームのロボットを傷つけたり変形させてはならない。 +
It is not allowed to damage or modify robots of other teams.

==== ボールやフィールドの損傷/Damaging The Field Or The Ball
フィールドやボールを損傷させたり変形させてはならない。 +
It is not allowed to damage or modify the field or the ball.

==== 手順の軽視/Disrespect Procedures
次に示すような行為を繰り返してはならない。 +
Not following defined procedures repetitively, like for example:

* 許可されていないにもかかわらず<<ハンドラー/Robot Handler, ハンドラー>>がロボットをフィールド内に投入する +
<<ハンドラー/Robot Handler, Robot handler>> puts a robot on the field, while it is not allowed
* ロボットが「ストップ」中にボールまでの距離要件を満たさない +
Robots do not keep required distance to the ball during stop
* ロボットが<<ペナルティーキック/Penalty Kick, ペナルティーキック>>中にルールで指定された位置要件を満たさず、手動で移動もしくは除去される必要がある +
Robots do not conform to the positioning rules during a <<ペナルティーキック/Penalty Kick, penalty kick>> and need to be moved or removed manually

==== 敬意の欠如/Showing Lack Of Respect
チームメンバーは試合に関わる全員に対して適切な敬意を示している必要がある。このルールの侵害には以下が含まれるがこれらに限定されない。 +
A team member must show appropriate respect to everyone involved in the game. Infringements of this rule include but are not limited to:

* 相手、<<主審/Referee, 主審>>またはその他<<公正な役割/Impartial Roles, 公平な役割>>の人を侮辱する +
insulting the opponent, the <<主審/Referee, referee>> or other persons holding an <<公正な役割/Impartial Roles, impartial role>>
* <<主審/Referee, 主審>>またはその他<<公正な役割/Impartial Roles, 公平な役割>>の人に迷惑をかける +
annoying the <<主審/Referee, referee>> or other persons holding an <<公正な役割/Impartial Roles, impartial role>>
* <<主審/Referee, 主審>>の指示に従わない +
not obeying the orders of the <<主審/Referee, referee>>

=== ファウル/Fouls
各チームのファウルの回数はカウンターにより追跡されている。
各ファウルはカウンターを1だけ増加させる。
ファウルカウンターが3増加する毎に<<イエローカード/Yellow Card, イエローカード>>が与えられる。 +
The number of fouls per team is tracked by a counter. Each foul will
increase the counter by one. Every third increase to the foul counter
causes a <<イエローカード/Yellow Card, yellow card>> to be awarded.

このセクションとサブセクションにある事項の違反は、特に明記されていない限りファウルのカウンターを増加させる。 +
Violations in this section and its subsections increase the foul counter if not stated otherwise.

NOTE: 人間の主審は、各セクションに記述された罰則に関係なく、そのファウルが繰り返される場合は<<イエローカード/Yellow Card, イエローカード>>を、特に極端な場合は<<レッドカード/Red Card, レッドカード>>を即座に与えることを選択できる。 +
Regardless, of the prescribed penalties in this section, if a
foul is severe or repeated, the referee can choose to immediately
issue a <<イエローカード/Yellow Card, yellow card>> or in extreme cases a <<レッドカード/Red Card,
red card>>.



==== 試合の停止を伴うファウル/Stopping Fouls
このセクションにあるファウルは試合を<<停止/Stop, 停止>>させ、反則が発生した時点でボールがあった位置から相手チームの<<フリーキック/Free Kick, フリーキック>>で再開する。 +
Fouls in this section cause the game to <<停止/Stop, stop>> and then resume
with a <<フリーキック/Free Kick, free kick>> for the opposite team from the position where the ball was
located when the foul began happening.

===== ロボットの相手ディフェンスエリアへの極端な接近/Robot Too Close To Opponent Defense Area
<<試合の再開/Resuming The Game, 試合を再開する>>前の、<<停止/Stop, 停止>>、<<フリーキック/Free Kick, フリーキック>>の間、すべてのロボットは相手の<<ディフェンスエリア/Defense Area, ディフェンスエリア>>から少なくとも0.2m以上離れていなければならない。 +
During <<停止/Stop, stop>> and <<フリーキック/Free Kick, free kicks>>, before the ball <<試合の再開/Resuming The Game, has entered play>>, all robots have to keep at least 0.2 meters distance to the opponent <<ディフェンスエリア/Defense Area, defense area>>.

ロボットが相手ディフェンスエリアから離れるため、2秒間の猶予が設けられる。 +
There is a grace period of 2 seconds for the robots to move away from the opponent defense area.

試合が停止(stop)状態もしくは<<フリーキック/Free Kick, フリーキック>>中で、インプレイになる前に同じチームによる2度目の反則があった場合は、試合は直ちに停止(halt)される。 +
The game is immediately halted after the second such foul committed by the same team while the game is stopped or during a <<フリーキック/Free Kick, free kick>>, before the ball has entered play.

NOTE: 最初の反則が<<フリーキック/Free Kick, フリーキック>>中に発生した場合、試合は通常通りに停止(stop)される。
猶予時間は同チームによる最初の反則後から再開される。
いずれの反則も、ファウルのカウンターを進める。
ロボットごとに個別の反則を取られることはない。 +
If the first foul is committed during a <<フリーキック/Free Kick, free kick>>, the game is still stopped regularly.
The grace period is restarted after the first foul of the same team.
Both fouls count towards the foul counter.
There are no individual fouls per robot.

===== プッシング/Pushing
あるロボットが相手のロボットに外力を加えて押していて、両方のロボットがボールもしくは互いに接触している(たとえば互いのロボットが相手のロボットの方向に移動している)時、これはプッシングの反則となる。 +
A robot pushes an opponent robot if both robots keep contact to the ball or to each other while the robot exerts force onto the opponent robot, such that both robots travel towards the opponent robot.

NOTE: 両方のロボットが同じような力で互いに押し合っている場合は、どちらに対してもファウルはとられない。 +
If both robots are pushing each other with similar force, no team is at fault.

===== ボールの保持/Ball Holding
ロボットは他のロボットがアクセスできないようにボールを囲んではならない。 +
Robots must not surround the ball to prevent access by others.

NOTE: (訳者注記)一般的に「ホールディング」と呼称されることが多い。

===== 転倒や部品の脱落/Tipping Over Or Dropping Parts
ロボットは他のロボットに潜在的な脅威を与えるように、フィールドで転倒したり、部品を脱落させてはならない。 +
A robot must not tip over, break or drop parts on the field that pose a potential threat to other robots.

ロボットがこのルールに違反した場合、<<ロボットの交代/Robot Substitution, ロボットの交代>>を行わなければならない。 +
A robot violating this rule has to be <<ロボットの交代/Robot Substitution, substituted>>.

NOTE: (例えばねじなどの)金属パーツと大きな部品は一般的に潜在的に脅威をもたらし、非常に小さい(例えば小車輪のゴムなどの)非金属のパーツはそうではない。 +
Metal parts (screws for example) as well as larger parts generally pose a potential threat, very small non-metal parts (for example rubber subwheel rings) don't.

===== マルチプルディフェンス/Multiple Defenders
NOTE: このルールは<<ファウル/Fouls, ファウル>>に対して定義された標準的な罰則を使用しない。 +
This rule does not use the standard sanctions defined for <<ファウル/Fouls, fouls>>.

キーパー以外のロボットは、自陣のディフェンスエリア外にとどまるよう最善を尽くさなければならない。
このルールの違反は非スポーツマン行為とみなされ得る。 +
Robots other than the keeper must maintain best-effort to fully stay outside the own defense area.
Infraction of this rule can be rated as unsporting behavior.

キーパー以外のロボットが自チームのディフェンスエリアに完全に入った状態でそのロボットがボールに触れた場合、試合は中断され、相手チームの<<ペナルティーキック/Penalty Kick, ペナルティーキック>>で試合を再開する。
ファウルのカウンターは増加 *しない*。 +
If a robot other than the keeper touches the ball while this robot is entirely
inside its own defense area, the game is stopped and a <<ペナルティーキック/Penalty Kick, penalty kick>> is awarded to the other team. The foul counter is *not*
increased.

===== 境界線との交差/Boundary Crossing
ロボットは、フィールド境界を越えてフィールド外に出るようにボールを蹴ってはならない。 +
A robot must not kick the ball over the field boundary such that the ball leaves the field.

===== キーパーによるボール保持/Keeper Held Ball
ボールはディヴィジョンAであれば5秒、ディヴィジョンBであれば10秒を超えて
<<ディフェンスエリア/Defense Area, ディフェンスエリア>>に留まってはならない。 +
The ball must not be kept in the <<ディフェンスエリア/Defense Area, defense area>> for more than
5 seconds (Division A) or 10 seconds (Division B).

===== ドリブルの超過/Excessive Dribbling
ロボットは<<ドリブルデバイス/Dribbling Device, ドリブル>>が開始されたボールの位置から直線距離で測定して1m以上ドリブルしてはならない。(ドリブルをした距離の測定方法としては)ロボットはボールと接触したときにドリブルを開始し、ボールとロボットの間に視認できるだけの間隔がある場合にドリブルを停止したものと見なす。 +
A robot must not <<ドリブルデバイス/Dribbling Device, dribble>> the ball further than 1 meter, measured linearly from the ball location where the dribbling started. A robot begins dribbling when it makes contact with the ball and stops dribbling when there is an observable separation between the ball and the robot.

NOTE: 人間のサッカー選手が頻繁に行うように、ロボットがボールを前に蹴るなどして定期的にボールの所有権を失う限り、ドリブラーを使用して長い距離をドリブルし続けることができる。 +
Dribblers can still be used to dribble large distances with the ball as long as the robot periodically loses possession, such as kicking the ball ahead of it as human soccer players often do.

NOTE: (訳者注記)一般的に「オーバードリブル」と呼称されることが多い。



==== 試合の停止を伴わないファウル/Non Stopping Fouls
このセクションにあるファウルは<<停止/Stop, 試合を停止しない>>。
代わりに、試合は通常どおり続行される。 +
Fouls in this section do not cause a <<停止/Stop, stop>>.
Instead, the game continues normally.

同一の「試合の停止を伴わないファウル」は、その違反状態が解消されるか、最初に違反が認定されてから2秒が経過するまでは処理されない。
これは、チームが追加のペナルティーを受ける前に、違反の原因となっているロボットの位置やボールスピードなどの特性を調整できるようにするためのものである。 +
The same no stop foul cannot be triggered again until the foul
condition has stopped being violated or there has been 2 seconds since
the foul was first triggered. This is to allow teams to adjust their
robots' positions, ball speed or any other property that is causing
the violation before being penalized additional times.

===== 相手ディフェンスエリア内でのアタッカーのボールへの接触/Attacker Touched Ball In Opponent Defense Area
ロボットが部分的にもしくは完全に相手チームの<<ディフェンスエリア/Defense Area, ディフェンスエリア>>にある間、そのロボットはボールに接触してはならない。 +
The ball must not be touched by a robot, while the robot is partially or fully inside the opponent <<ディフェンスエリア/Defense Area, defense area>>.

===== ボール速度/Ball Speed
ロボットは3D空間内で6.5m/s以上の速さでボールをシュートしてはならない。 +
A robot must not accelerate the ball faster than 6.5 meters per second in 3D space.

===== 衝突/Crashing
異なるチームの2つのロボットの衝突の瞬間に、両方のロボットの速度ベクトルの差が取られ、両方のロボットの位置によって定義される線上に投影される。この投影の長さが1.5m/sを超えるた場合、より速いロボットにファウルを与える。ロボットの絶対速度の差が0.3m/s未満であれば、どちらにもファウルを与える。 +
At the moment of collision of two robots of different teams, the difference of the speed vectors of both robots is taken and projected onto the line that is defined by the position of both robots. If the length of this projection is greater than 1.5 meters per second, the faster robot committed a foul. If the absolute robot speed difference is less than 0.3 meters per second, both conduct a foul.



==== アウトオブプレイ中のファウル/Fouls While Ball Out Of Play
このセクションにあるファウルはボールが<<インプレイとアウトオブプレイ/Ball In And Out Of Play, アウトオブプレイ>>の時にのみ発生する。 +
Fouls in this section can only occur when the ball is <<インプレイとアウトオブプレイ/Ball In And Out Of Play, out of play>>.

各ファウルには、再度ファウルとなるまでチームごとに2秒の猶予時間がある。 +
Each foul has a grace period of 2 seconds per team until it is raised again.

NOTE: 複数のロボットが同じファウルを2秒以内に行った場合、最初のファウルのみが計上される。 +
If multiple robots commit the same foul within 2 seconds, only the first foul counts.

NOTE: ロボットがファウルを続ける場合、猶予時間後に再び罰則が与えられる。 +
If a robot keeps committing a foul, it will be punished again after the grace period.

===== ディフェンダーのボールへの極端な接近/Defender Too Close To Ball
相手チームの<<キックオフ/Kick-Off,  キックオフ>>もしくは<<フリーキック/Free Kick, フリーキック>>の間、ロボットはボールから少なくとも0.5m以上離れなければならない。
このファウルが犯された時、相手チームがボールをインプレイにするまでのタイマーはリセットされる。 +
A robot's distance to the ball must be at least 0.5 meters during an opponent <<キックオフ/Kick-Off, kick-off>> or <<フリーキック/Free Kick, free kick>>.
When the foul is committed, the timer of the opponent team for bringing the ball into play is reset.

<<主審/Referee, 人間の主審>>は、著しい妨害を受けた<<キックオフ/Kick-Off, キックオフ>>もしくは<<フリーキック/Free Kick, フリーキック>>をやり直す事ができる。 +
The <<主審/Referee, human referee>> may decide to repeat the <<キックオフ/Kick-Off, kick-off>> or <<フリーキック/Free Kick, free kick>> on significant disturbances.

NOTE: <<停止/Stop, ストップゲーム>>中は、ボールに近すぎる事に対する自動的な罰則はない。主審はチームが必要な距離を守っていない場合、<<イエローカード/Yellow Card, イエローカード>>を発行することで非スポーツマン行為を罰することができる。詳しい説明は「<<停止/Stop, 停止>>」を参照する事。 +
During <<停止/Stop, stop>>, there is no automatic sanction for being too close to the ball. The referee may still punish a team for <<非スポーツマン行為/Unsporting Behavior,unsporting behavior>> by issuing a <<イエローカード/Yellow Card, yellow card>> if it does not respect the required distance. See <<停止/Stop, stop>> for further explanation.

===== ストップ中のロボットの速度/Robot Stop Speed
ロボットはストップゲーム中は1.5m/s以上で動いてはならない。このルールの反則は<<停止/Stop, ストップゲーム>>1回につき1台のロボットに対してカウントされる。 +
A robot must not move faster than 1.5 meters per second during <<停止/Stop, stop>>. A violation of this rule is only counted once per robot and stoppage.

ロボットが減速する猶予時間は2秒である。 +
There is a grace period of 2 seconds for the robots to slow down.

NOTE: このルールは<<ボール配置/Ball Placement, ボール配置>>には適用されない。 +
This rule does not apply to <<ボール配置/Ball Placement, ball placement>>.

NOTE: 「ストップ」コマンドは手動でのボール配置と<<ロボットの交代/Robot Substitution, ロボットの交代>>に使用されるため、ロボットの速度制限の意図は、ロボットがフィールド内にいる人間を傷つけないようにする事にある。 +
Since the stop command is used for manual ball placement and
<<ロボットの交代/Robot Substitution, robot substitution>>, the intention of the robot
speed limit is to avoid robots harming the people on the field.

===== ボール配置への干渉/Ball Placement Interference
<<ボール配置/Ball Placement, ボール配置>>の間、配置を担当しないチームのすべてのロボットはボールと配置位置を結ぶラインから少なくとも0.5mは離れなければならない(この領域はスタジアム状の形になる)。 +
During <<ボール配置/Ball Placement, ball placement>>, all robots of the non-placing team have to keep at least 0.5 meters distance to the line between the ball and the placement position (the forbidden area forms a stadium shape).

ボール配置を担当しないチームのロボットが2秒以上に亘ってボールと配置場所を結ぶラインに接近した場合、ファウルとなる。この場合、ボール配置を行える時間が10秒だけ追加される。
1回のボール配置フェイズにつき1度の干渉のみをファウルとして計上する。ただしボール配置の猶予時間は干渉が起こるたびに延長される。 +
If a robot of the non-placing team is too close to the line between
the ball and the placement position for more than 2 seconds, it
commits a foul. In this case, 10 seconds are added to the ball
placement timer.
Only one interference foul per ball placement phase counts towards the foul counter, but the placement timer is always incremented.

NOTE: このルールは、ボール配置への干渉をすべてカバーするものではない。
<<主審/Referee, 主審>>はボール配置を担当しないチームが明らかにボール配置に干渉している場合は、ファウルを宣告することが推奨される。 +
This rule does not cover all cases of ball placement interference.
The <<主審/Referee, referee>> is encouraged to call fouls if the non-placing team is obviously interfering with the ball placement.

NOTE: もしロボットが(たとえば立ち往生を起こした、動作できない、など)干渉を続ける場合、人間の審判はボール配置を止めて手動でボールを配置することが推奨される。 +
If a robot keeps interfering the ball placement (for example if it is stuck or can not move), the human referee is encouraged to stop the placement and place the ball manually.

===== ロボット交代回数超過/Excessive Robot Substitutions
チームが自由に行えるロボットの交代権を使い切った場合、それ以降のすべてのロボット交代はファウルとなる。
試合は相手チームの <<コーナーキック/Corner Kick, コーナーキック>> で再開される。
もし両チームが同一の<<停止/Stop, ストップゲーム>>中にこのファウルをとられた場合、試合はもとのコマンドで再開される。 +
If a team has used up their free robot substitution budget, every additional robot substitution is a foul.
The match is resumed with a <<コーナーキック/Corner Kick, corner kick>> for the opponent team.
If both teams committed this foul in the same <<停止/Stop, stop>>, the match is resumed with the original command.