== Playing Environment

=== Field Setup
==== Dimensions
The field of play must be rectangular and of the following size:

* Division A: 13.4 meters times 10.4 meters with a playing area of 12 meters times 9 meters
* Division B: 10.4 meters times 7.4 meters with a playing area of 9 meters times 6 meters

The exact field dimensions and the field markings at the venue may vary by up to ±10% in each linear dimension.

The two figures below show the dimensions of the field, the goals and special field areas, measured in millimeters.  <<field-dimensions-a, Figure 1>> shows the dimensions for division A and  <<field-dimensions-b, figure 2>> for division B.

NOTE: The numbers in the figures below show the distances in millimeters.

[[field-dimensions-a]]
.Field dimensions and markings for division A
image::quad-size-field.svg[]

[[field-dimensions-b]]
.Field dimensions and markings for division B
image::double-size-field.svg[]

==== Field Surface
The playing surface is green felt mat or carpet. The floor under the carpet is level, flat, and hard.

The field surface will continue for 0.7 meters beyond the <<Field Lines, field lines>> on all sides. The outer 0.4 meters of this runoff area, separated from the robot area by a 0.1 meters tall wall, is used as a designated walking area for the <<Referee, referee>> and the <<Assistant Referee, assistant referee>>. The remaining 0.3 meters are the field margins.


==== Field Markings
The field of play is marked with lines. All lines are 0.01 meters wide and white (paint, spray, white carpet or strong tape). Lines belong to the areas of which they are boundaries.

===== Field Lines
The playing area is defined by four field lines. The two longer field lines are called touch lines. The two shorter field lines are called goal lines.

===== Additional Lines
The field of play is divided into two halves by a halfway line that runs along the width of the field and through the center of the field. The halfway line is parallel to the goal lines.

A mid-line runs along the length of the field, passing through the center of the field. The mid-line is parallel to the touch lines. This line is used to provide adequate features for the geometry calibration of the <<Vision, vision software>>.

===== Center Circle
The center mark is indicated at the midpoint of the halfway line. A circle with a diameter of 1 meter is marked around it for both divisions.

===== Defense Area
A defense area is defined as a rectangle touching the goal lines centrally in front of both <<Goals, goals>>. The size of the defense area is 2.4 meters times 1.2 meters for division A and 2 meters times 1 meter for division B, as shown in figures <<field-dimensions-a, 1>> and <<field-dimensions-b, 2>> respectively.


===== Penalty Mark
For each field half the penalty mark is on the <<Additional Lines, mid-line>> (not halfway line), 8 meters (division A) or 6 meters (division B) away from the opponent goal center.


==== Goals
Goals must be placed on the center of each goal line and anchored securely to the field surface. They consist of two 0.16 meters high vertical side walls joined at the back by a 0.16 meters high vertical rear wall. The inner face of the goal has to be covered with an energy absorbing material such as foam to help absorb ball impacts and lessen the speed of deflections. The goal walls, edges, and tops are white in color.

The distance between the side walls is 1.2 meters for division A and 1 meter for division B, and the goal is 0.18 meters deep. The goal walls are 0.02 meters thick and touch the goal line, but do not overlap or encroach on the field lines or the field. <<goal-detail-a, Figure 3>> and <<goal-detail-b, figure 4>> show these details for division A and division B respectively.

NOTE: The numbers in the figures below show the distances in millimeters.

[[goal-detail-a]]
.The goal in detail for division A
image::goal_detail_divisionA.svg[width=400]

[[goal-detail-b]]
.The goal in detail for division B
image::goal_detail_divisionB.svg[width=400]

=== Ball
The ball is a standard orange golf ball. It weights approximately 0.046 kilograms and its diameter measures 0.043 meters.

For official matches, the <<Organizing Committee, organizing committee>> provides the ball.

=== Shared Software
The shared software used in the Small Size League is maintained by the <<Technical Committee, technical committee>>, though everyone is encouraged to contribute. The <<Technical Committee, technical committee>> members however guarantee that any changes made less than three months before the next RoboCup do not break compatibility.

==== Vision
Each field is provided with a shared central vision server and a set of shared cameras. This shared vision equipment uses the community-maintained SSL-Vision software (https://github.com/RoboCup-SSL/ssl-vision) to provide localization data to teams via Ethernet in a packet format that is to be announced by the shared vision system developers before the competition. Teams need to ensure that their systems are compatible with the shared vision system output and that their systems are able to handle the typical properties of real-world sensory data as provided by the shared vision system (including noise, latency, or occasional failed detections and misclassifications). The vision patterns on the top of the robots must adhere to the specifications of SSL-Vision, and must be of the standard color paper as specified in the SSL-Vision documentation.

Besides the shared vision equipment, teams are not allowed to mount their own cameras or other external sensors, unless specifically announced or permitted by the respective competition organizers.

==== Game Controller
A game is controlled by the community-maintained ssl-game-controller (https://github.com/RoboCup-SSL/ssl-game-controller).
It is operated by the <<Game Controller Operator, game controller operator>>. The software translates decisions of the <<Referee, referee>> and the <<Automatic Referee, automatic referee>> into Ethernet communication signals that are broadcast to the network. It maintains the state of the game, tracks all events and acts as a proxy between all participating parties in the game.

The game-controller has a network interface for the playing teams. They can automatically <<Choosing Keeper Id, change their keeper id>>, they can signal a robot substitution intent for the next opportunity and they can reply to requests of the <<Advantage Rule, advantage rule>>.

==== Automatic Referee
One or more automatic referee applications can supervise a game and report <<Offenses, offenses>> to the <<Game Controller, game controller>>.
At least one automatic referee is required per game. If more than one automatic referee is connected to the game controller, a majority vote can be applied.

New automatic referee implementations can be provided, given that the source code is open-sourced. New implementations must be announced at least three months before the competition. The <<Technical Committee, technical committee>> decides if an implementation will be used or not.

The <<Game Event Table>> shows which game events an automatic referee implementation must be able to detect.

Existing implementations can be found on Github: https://github.com/RoboCup-SSL/ssl-autorefs.

=== Communication Flags

The communication flags are used to avoid gesturing and yelling with the <<Referee, referee>> during a match.
These flags are responsible for communicating various intents, such as: <<Timeouts, timeouts>>, <<Emergency stop, emergency stops>>, <<Robot Substitution, manual robot substitution>> and <<Challenge Flags, challenges>>.

The <<Referee, referee>> or <<Game Controller Operator, game controller operator>> has to acknowledge the communication flag.
Any gesturing and yelling will be considered <<Unsporting Behavior, unsporting behavior>>, punished by a <<Red Card, red card>> after the first warning.

The communication flags are provided by the organizers of the competition.
A remote control software or device can be provided and replace physical flags.
Any other solution that the organizers find feasible can also be used.
