== Referee Commands

=== Stopping The Game

==== Stop
.Definition
When the STOP command is issued, all robots have to slow down to less than 1.5 m/s. Additionally, all robots have to keep at least 500mm distance to the ball and are not allowed to manipulate the ball.

NOTE: If the ball moves very quickly, it is hard to always keep the required distance to the ball, especially since the speed of the robots is limited during STOP. Therefore, it is sufficient if it is obvious to the referee that the robots try their best to follow the distance rule.

.Usage
The STOP command is used to pause the game after the ball crossed the field boundaries (including goals) or a foul occured as well as to prepare the start or resumption of the game after HALT, timeouts and automatic ball placement.



==== Halt
.Definition
When the HALT command is issued, all robots have to brake immediately. During HALT, the robots are not allowed to move or manipulate the ball.

.Usage
The HALT command allows the referee to interrupt the game immediately whenever an emergency occurs (for example when a robot gets out of contol). It is
also used to recalibrate the vision software during a game if the vision expert considers it necessary and the referee agrees. Additionally, the referee is free to issue the HALT command at will.

The HALT command is always followed up by STOP.

=== Resuming The Game
To resume the game after a stoppage or start the game in the first place, the ball has to be placed at a certain position on the field first. The main referee or assistant referee is advised to use a so-called ball handler (a long, preferably black stick-like device) to move the ball.

In Division A, the ball will be placed automatically by the robots if the following command is a free kick or FORCE START (see <<Automatic Ball Placement>>).


==== Kick-Off
Chapter 8.2

==== Indirect Free Kick
Chapter 13

==== Direct Free Kick
Chapter 13

==== Force Start
.Definition
When the FORCE START command is issued, the game is immediately resumed and both teams are allowed to manipulate the ball again.

.Usage
The referee can issue a STOP command followed by FORCE START if there is a clear lack of progress for at least 10 seconds while both teams are allowed to manipulate the ball. This is not the case if the ball is inside a defense area.

It can also be used to resume the game when the game had to be stopped and no team or both teams are at fault.

==== Penalty Shot
Chapter 14

=== Sanctions
==== Yellow Card
Chapter 12.4

==== Red Card
Chapter 12.4

==== Forced Forfeit
==== Disqualification


=== Special Commands

==== Automatic Ball Placement
Chapter 9.2

.Definition

.Usage

==== Shoot-Out
Appendix A.2

