== Referee Commands

=== Stopping The Game

==== Stop
.Definition
When the STOP command is issued, all robots have to slow down to less than 1.5 m/s. Additionally, all robots have to keep at least 0.5 meters distance to the ball and are not allowed to manipulate the ball.

NOTE: If the ball moves very quickly, it is hard to always keep the required distance to the ball, especially since the speed of the robots is limited during STOP. Therefore, it is sufficient if it is obvious to the referee that the robots try their best to follow the distance rule.

.Usage
The STOP command is used to pause the game after the ball crossed the field lines (including goals) or a foul occured as well as to prepare the start or resumption of the game after HALT, timeouts and automatic ball placement. The robot speed limit and the minimum distance to the ball allow the referee or assistant referee to place the ball safely and without interference.



==== Halt
.Definition
When the HALT command is issued, all robots have to brake immediately. During HALT, the robots are not allowed to move or manipulate the ball.

.Usage
The HALT command allows the referee to interrupt the game immediately whenever an emergency occurs (for example when a robot gets out of contol). It is
also used to recalibrate the vision software during a game if the vision expert considers it necessary and the referee agrees. Additionally, the referee is free to issue the HALT command at will.

The HALT command is always followed up by STOP.

=== Resuming The Game
To resume the game after a stoppage or start the game in the first place, the ball has to be placed at a certain position on the field first. The main referee or assistant referee is advised to use a so-called ball handler (a long, preferably black stick-like device) to move the ball.

In Division A, the ball will be placed automatically by the robots if the following command is a free kick or FORCE START (see <<Automatic Ball Placement>>).

==== Kick-Off
.Definition
The ball has to be placed at the center of the field.

When the KICK-OFF command is issued, all robots have to move to their own half of the field excluding the center circle. However, one robot of the attacking team is also allowed to be inside the whole center circle. This robot will be referred to as the kicker. No robot is allowed to touch the ball.

When the NORMAL START command is issued, the kicker is allowed to shoot the ball. A goal may be scored directly from the kick-off.

When the ball is in play, the kicker may not touch the ball until it has been touched by another robot or the game has been stopped (see <<Double Touch, double touch>>). Also, the restrictions regarding the robot positions are lifted.

.Usage
Both half times as well as both extra time periods (if needed) start with a kick-off. Chapter <<Game preparation>> describes how to determine the attacking team.

Additionally, after a goal has been scored, the receiving team restarts the game with a kick-off.

==== Direct Free Kick
.Definition
The ball placement position for a free kick depends on the event that led to the free kick. This position is valid if there is at least 0.2 meters distance to all field lines and 1 meter distance to either defense area. If an event requires the ball to be placed at a position that contravenes this rule, it has to be placed at the closest valid position instead.

When the DIRECT FREE KICK command is issued, robots of the attacking team are allowed to approach the ball while robots of the defending team still have to stay at least 0.5 meters distance away from the ball (the same distance as in STOP). One robot of the attacking team is allowed to shoot the ball. This robot will be referred to as the kicker. A goal may be scored directly from the direct free kick.

When the ball is in play, the kicker may not touch the ball until it has been touched by another robot or the game has been stopped (see <<Double Touch, double touch>>). Also, the restrictions regarding the robot positions are lifted.

.Usage
Direct free kicks are used to restart the game after a <<Fouls, foul>> has occured. Additionally, <<Goal Kick, goal kicks>> and <<Corner Kick, corner kicks>> are mapped to direct free kicks.

==== Indirect Free Kick
.Definition
An indirect free kick behaves like a direct free kick, except: After an indirect free kick, a goal can only be scored if the ball touches a robot of the attacking team after the ball entered play and before it entering the goal. If the ball enters the goal without touching an attacking robot, it will be treated like it crossed the goal line outside the goal.

NOTE: Scoring a goal from an indirect free kick does not require more than one attacking robot. The goal can also be shot by the same robot that kicked the free kick if a robot of the defending team touches the ball before the attacker shoots the goal.

NOTE: In association football, it is sufficient if any player (including the keeper) touches the ball before it enters the goal. To discourage the teams to shoot directly at the goal and hope that the keeper touches it, the rules of the Small Size League require a second touch of an attacking robot.

.Usage
Indirect free kicks are used to restart the game after a <<Minor Offenses, minor offense>> has occured. Additionally, <<Throw-In, throw-ins>> are mapped to indirect free kicks.

==== Force Start
.Definition
When the FORCE START command is issued, the game is immediately resumed and both teams are allowed to manipulate the ball again.

.Usage
The referee can issue a STOP command followed by FORCE START if there is a clear lack of progress for at least 10 seconds while both teams are allowed to approach and manipulate the ball.

It can also be used to resume the game when the game had to be stopped and no team or both teams are at fault.

==== Penalty Kick
.Definition
To initiate a penalty kick, the STOP command has to be sent and the ball has to be placed on the penalty mark by the human referee.

When the PENALTY command is issued, one attacking robot is allowed to approach but not touch the ball. This robot will be referred to as the kicker. The defending keeper has to touch the goal line. All other robots have to move behind a line parallel to the goal line and 0.4 meters behind the penalty mark. When these constraints are met, the referee may continue with a NORMAL START command.

When the NORMAL START command is issued, the kicker is allowed to shoot the ball. A goal may be scored directly from the penalty kick.

When the ball is in play, the kicker may not touch the ball until it has been touched by another robot or the game has been stopped (see <<Double Touch, double touch>>). Also, the restrictions regarding the robot positions are lifted.

Additional time is allowed for a penalty kick to be taken at the end of each half or at the end of periods of extra time.

The penalty kick is retaken if the attacking team infringes the rules and the ball enters the goal or the defending team infringes the rules and the ball does not enter the goal.

.Usage
Penalty Kicks are used to punish teams that received multiple <<Yellow Card, yellow cards>>.

// TODO multiple defenders


=== Sanctions

==== Yellow Card
.Definition
A yellow card can only be given during STOP.

Upon receipt of a yellow card, the number of robots allowed on the field for the penalised team decreases by one. If, after this decrease, the team has more robots than permitted on the field, a robot must immediately be removed from the field before play resumes. The penalized team can choose the robot to remove.

After 2 minutes of playing time, the yellow card expires and the number of allowed robots is increased by one.

For every third card (regardless of its color) for one team, a penalty kick is awarded to the opponent team.

.Usage
Yellow Cards are used to punish teams that committed multiple <<Fouls, fouls>>.

Yellow Cards can also be given by the referee to punish fouls or unsporting behavior.

==== Red Card
.Definition
A red card behaves like a <<Yellow Card, yellow card>>, exept: It does not expire until the end of the game.

.Usage
Red Cards are given by the referee to punish severe fouls or unsporting behavior.

NOTE: Offenses that can result in a red card include serious violent contact by the robots and disrespectful behaviour towards the referees.


==== Forced Forfeit
.Definition
A Forced Forfeit means that a team instantly loses the current game with a score of 0 to 10.

.Usage
A team can be forced to forfeit if it is unable to play with at least one robot that satisfies the rules.

A team can only be forced to forfeit in agreement with members of the technical committe and the organizing committee.

==== Disqualification
.Definition
A Disqualification means that a team immediately drops out of the tournament and places last. It will not be eligible to receive any trophies.

.Usage
A team can be disqualified if members of this team don't follow safety guidelines, rules of the venue or commit similarly severe offenses.

A team can only be disqualified in agreement with members of the technical committe and the organizing committee.

=== Special Commands

==== Automatic Ball Placement
Chapter 9.2

.Definition

.Usage

==== Shoot-Out
Appendix A.2

