== Referee Commands

=== Stopping The Game
When the game is stopped, the ball is considered out of play until it has been brought <<Resuming The Game, into play>>.

The game time is paused during <<Stop, stop>>, <<Halt, halt>> and <<Ball Placement, ball placement>>.

NOTE: The game time is not paused during other referee commands, even if the ball is still out of play.

==== Stop
.Definition
When the stop command is issued, all robots have to slow down to less than 1.5 m/s. Additionally, all robots have to keep at least 0.5 meters distance to the ball and are not allowed to manipulate the ball.

NOTE: If the ball moves very quickly, it is hard to always keep the required distance to the ball, especially since the speed of the robots is limited during stop. Therefore, it is sufficient if it is obvious to the referee that the robots try their best to follow the distance rule.

.Usage
The stop command is used to pause the game after the ball crossed the <<Field Lines, field lines>> (including goals) or an offense occurred as well as to prepare the start or resumption of the game after halt, timeouts and automatic ball placement. The robot speed limit and the minimum distance to the ball allow the referee or assistant referee to place the ball safely and without interference.



==== Halt
.Definition
When the halt command is issued, no robot is allowed to move or manipulate the ball.

There is a grace period of 2 seconds for the robots to brake.

.Usage
The halt command allows the referee to interrupt the game immediately whenever an emergency occurs (for example when a robot gets out of contol). It is
also used to recalibrate the vision software during a game if the vision expert considers it necessary and the referee agrees and for <<Robot Substitution, robot substitution>>. Additionally, the referee is free to issue the halt command at will.

The halt command is always followed up by stop.

=== Resuming The Game
To resume the game after a stoppage or start the game in the first place, the ball has to be placed at a certain position on the field first. The main referee or assistant referee is advised to use a so-called ball handler (a long, preferably black stick-like device) to move the ball.

In division A, the ball will be placed automatically by the robots if the following command is a free kick or force start (see <<Ball Placement>>).

When <<Force Start, force start>> has been issued or the ball moved at least 0.05 meters following a <<Kick-Off, kick-off>>, <<Direct Free Kick, direct free kick>>, <<Indirect Free Kick, indirect free kick>> or <<Penalty Kick, penalty kick>>, the ball is considered in play (see <<Double Touch>> for the rationale of the 0.05 meter distance).

==== Kick-Off
.Definition
The ball has to be placed in the center of the field by the human referee.

When the kick-off command is issued, all robots have to move to their own half of the field excluding the <<Center Circle, center circle>>. However, one robot of the attacking team is also allowed to be inside the whole center circle. This robot will be referred to as the kicker. No robot is allowed to touch the ball.

When the normal start command is issued, the kicker is allowed to shoot the ball. A goal may be scored directly from the kick-off.

When the ball is <<Resuming The Game, in play>>, the kicker may not touch the ball until it has been touched by another robot or the game has been stopped (see <<Double Touch, double touch>>). Also, the restrictions regarding the robot positions are lifted.

.Usage
Both half times as well as both overtime periods (if needed) start with a kick-off. Chapter <<Match Preparation>> describes how to determine the attacking team.

Additionally, after a goal has been scored, the receiving team restarts the game with a kick-off.

==== Direct Free Kick
.Definition
The ball placement position for a free kick depends on the event that led to the free kick. This position is valid if there is at least 0.2 meters distance to all <<Field Lines, field lines>> and 1 meter distance to either <<Defense Area, defense area>>. If an event requires the ball to be placed at a position that contravenes this rule, it has to be placed at the closest valid position instead.

When the direct free kick command is issued, robots of the attacking team are allowed to approach the ball while robots of the defending team still have to stay at least 0.5 meters distance away from the ball (the same distance as in stop). One robot of the attacking team is allowed to shoot the ball. This robot will be referred to as the kicker. A goal may be scored directly from the direct free kick.

When the ball is <<Resuming The Game, in play>>, the kicker may not touch the ball until it has been touched by another robot or the game has been stopped (see <<Double Touch, double touch>>). Also, the restrictions regarding the robot positions are lifted.

.Usage
Direct free kicks are used to restart the game after a <<Fouls, foul>> has occured. Additionally, <<Goal Kick, goal kicks>> and <<Corner Kick, corner kicks>> are mapped to direct free kicks.

==== Indirect Free Kick
.Definition
An indirect free kick behaves like a <<Direct Free Kick,direct free kick>>, except: After an indirect free kick, a goal can only be scored if the ball touches a robot of the attacking team after the ball <<Resuming The Game, entered play>> and before it entering the goal of the defending team. If the ball enters the goal of the defending team without touching an attacking robot, it will be treated like it crossed the goal line outside the goal.

If the ball enters the goal of the attacking team (an own goal), a goal will be awarded to the defending team.

NOTE: Scoring a goal from an indirect free kick does not require more than one attacking robot. The goal can also be shot by the same robot that kicked the free kick if a robot of the defending team touches the ball before the attacker shoots the goal.

NOTE: In association football, it is sufficient if any player (including the keeper) touches the ball before it enters the goal. To discourage the teams to shoot directly at the goal and hope that the keeper touches it, the rules of the Small Size League require a second touch of an attacking robot.

.Usage
Indirect free kicks are used to restart the game after a <<Minor Offenses, minor offense>> has occured. Additionally, <<Throw-In, throw-ins>> are mapped to indirect free kicks.

==== Force Start
.Definition
When the force start command is issued, the game is immediately resumed and both teams are allowed to approach and manipulate the ball again.

.Usage
The referee can issue a stop command followed by force start if there is a clear lack of progress for at least 10 seconds while both teams are allowed to approach and manipulate the ball.

It can also be used to resume the game when the game had to be stopped and no team or both teams are at fault.

==== Penalty Kick
.Definition
To initiate a penalty kick, the stop command has to be sent and the ball has to be placed on the <<Penalty Mark, penalty mark>> by the human <<Referee, referee>>.

When the penalty command is issued, one attacking robot is allowed to approach but not touch the ball. This robot will be referred to as the kicker. The defending keeper has to touch the goal line. All other robots have to move behind a line parallel to the goal line and 0.4 meters behind the penalty mark. When these constraints are met, the referee may continue with a normal start command.

When the normal start command is issued, the kicker is allowed to shoot the ball. A goal may be scored directly from the penalty kick.

When the ball is <<Resuming The Game, in play>>, the kicker may not touch the ball until it has been touched by another robot or the game has been stopped (see <<Double Touch, double touch>>). Also, the restrictions regarding the robot positions are lifted.

Additional time is allowed for a penalty kick to be taken at the end of each half or at the end of periods of overtime.

The penalty kick is retaken if the attacking team infringes the rules and the ball enters the goal or the defending team infringes the rules and the ball does not enter the goal.

.Usage
Penalty Kicks are used to punish teams that received multiple <<Yellow Card, yellow cards>>, as well as to punish <<Unsporting Behavior, unsporting behavior>> and <<Multiple Defenders, multiple defenders>>.


=== Sanctions

==== Yellow Card
.Definition
A yellow card can only be given during <<Halt, halt>>.

If the yellow card is shown as a result of <<Unsporting Behavior, unsporting behavior>>, the referee may decide to immediately <<Halt, halt>> the match. In this case, the match continues with a direct free kick for the other team.

Upon receipt of a yellow card, the number of robots allowed on the field for the penalised team decreases by one. If, after this decrease, the team has more robots than permitted on the field, a robot must be <<Robot Substitution, taken out>> before <<Resuming The Game, play resumes>>. The penalized team can choose the robot to remove.

After 120 seconds of playing time (measured by the game controller), the yellow card expires and the number of allowed robots is increased by one. The team may <<Robot Substitution, put a robot back in>> during the next opportunity.

For every third card (regardless of its color) for one team, a <<Penalty Kick, penalty kick>> is awarded to the opponent team.

.Usage
Yellow cards are used to punish teams that committed multiple <<Fouls, fouls>>.

Yellow cards can also be given by the referee to punish <<Fouls, fouls>> or <<Unsporting Behavior,unsporting behavior>>.

==== Red Card
.Definition
A red card behaves like a <<Yellow Card, yellow card>>, exept: It does not expire until the end of the game.

.Usage
Red cards are given by the referee to punish severe <<Fouls, fouls>> or <<Unsporting Behavior,unsporting behavior>>.

NOTE: For example, serious violent contact by the robots or disrespectful behaviour towards the referees can result in a red card.


==== Forced Forfeit
.Definition
A Forced forfeit means that a team instantly loses the current game with a score of 0 to 10.

.Usage
A team can be forced to forfeit if it is unable to play with at least one robot that satisfies the rules.

A team can only be forced to forfeit in agreement with members of the <<Technical Committee, technical committee>> and the <<Organizing Committee, organizing committee>>.

==== Disqualification
.Definition
A Disqualification means that a team immediately drops out of the tournament and places last. It will not be eligible to receive any trophies.

.Usage
A team can be disqualified if members of this team don't follow safety guidelines, rules of the venue or commit similarly severe offenses.

A team can only be disqualified in agreement with members of the <<Technical Committee, technical committee>> and the <<Organizing Committee, organizing committee>>.

=== Special Commands

==== Ball Placement
.Definition
After the game was stopped, the ball must be placed on the appropriate position, depending on the event that occurred.
The automatic ball placement is the preferred way to place the ball at the designated position on the field by the robots of the teams without human interaction.
If this is not possible, the <<Referee, referee>> places the ball manually.

A ball is considered placed successfully by the robots if

* no more than 30 seconds passed since the placement command
* there is no robot within 0.05 meters distance to the ball if the next command is an <<Indirect Free Kick, indirect free kick>> or <<Direct Free Kick, direct free kick>>
* there is no robot within 0.5 meters distance to the ball if the next command is a <<Force Start, force start>>
* the ball is stationary
* the ball is at a position within 0.15 meters radius from the requested position

No further commands will be issued by the <<Game Controller, game controller>> until the automatic placement is complete.
The game will be continued by the <<Game Controller, game controller>> as soon as the ball is successfully placed.
A failed placement will result in an indirect free kick for the opposing team.
If this team failed to place the ball as well, the ball is placed by the <<Referee, referee>> and game continues with the original command.

The non-placing team must not <<Ball Placement Interference, interfere the ball placement task>>.

.Usage
When the ball goes <<Stopping The Game,out of play>>, the following rules decide, if automatic ball placement is applied:

. The <<Referee, referee>> has to place the ball for all kickoffs and all penalty kicks
. For an <<Indirect Free Kick, indirect free kick>> or <<Direct Free Kick, direct free kick>>, the team that brings the ball into play must place the ball
. For a <<Force Start, force start>>, a team is drawn by chance and must place the ball
. The ball must be visible and must not be inside a field or goal corner or behind the goal, before the ball placement starts
. The <<Referee, referee>> can decide to place the ball manually at any time
. The <<Referee, referee>> can decide to disable automatic ball placement for the rest of the game. TC/OC must agree with this decision
. When a team has failed to place the ball five times in a row, it is not allowed to place the ball for the rest of the game half. All free kicks that were a result of the ball leaving the field, are awarded to the opposing team. For all other rule violations or when both teams failed to place the ball, the ball is placed by the <<Referee, referee>>
. If no team can place the ball, the ball is placed by the <<Referee, referee>>

NOTE: The ball may still be moving when the placement command is issued.

Ball placement is mandatory for all teams in division A.
Teams in division B may decide, at any time before or during the game, not to place the ball for the rest of the game by talking to the <<Referee, referee>>, who in turn tells the <<Game Controller Operator, game controller operator>> to disable ball placement for this team.
In this case, the team is allowed to bring the ball into play, after the ball was placed by the opposing team.
If the opposing team fails to place the ball or no team can place the ball, it is placed by the <<Referee, referee>>.

==== Shoot-Out
.Definition
Both teams alternately attempt to score a goal until each team has performed 5 attempts. If both teams have the same score after those 5 attempts, each team takes another attempt in the same order as before until the score of the two teams is different.

Only one attacking robot and one keeper is allowed per team. During a shoot-out attempt, the attacking robot and the opponent keeper are the only ones allowed to move and manipulate the ball. Other robots are not allowed to interfere.

The procedure of a shoot-out attempt is as follows:

. The ball is placed by the human referee on the <<Additional Lines, mid-line>> (not halfway line), 8 meters (division A) or 6 meters (division B) away from the opponent goal.
. When the <<Penalty Kick, penalty>> command is issued, the defending keeper has to move to the goal line and keep touching it.
. When the normal start command is issued, the attacker is allowed to manipulate the ball. The ball has to only move towards the opponent goal, as measured by its x coordinate in the coordinate system of <<Vision, SSL-Vision>>.
. When the ball is <<Resuming The Game, in play>>, the defending keeper may move freely again, analogous to a <<Penalty Kick, penalty kick>>.

A goal is awarded if:

* the ball enters the goal of the defending team in less than 10 seconds, starting from when the <<Penalty Kick, penalty>> command is issued
* the defending team violates any rule

A goal is not awarded if:

* the ball crosses any <<Field Lines, field lines>> outside the goal
* the defending keeper touches the ball such that the ball speed vector changes direction by at least 90 degrees in 2D space
* the attacking team violates any rule

NOTE: The restrictions defined for <<Scoring Goals, scoring goals>> do not apply here. Other rules like the <<Dribbling, dribbling>> limitation for example do.

Robots may be <<Robot Substitution, substituted>> between shoot-out attempts. The new robot may be put in right away.

NOTE: Note that <<Timeouts, timeouts>> are not allowed during shoot-out.

.Usage
Shoot-Out is used to determine the winner of an elimination match if both teams scored the same amount of goals in previous <<Game Stages, game stages>>.

