== Referee Commands

=== Stopping The Game

==== Stop
.Definition
When the STOP command is issued, all robots have to slow down to less than 1.5 m/s. Additionally, all robots have to keep at least 500mm distance to the ball and are not allowed to manipulate the ball.

NOTE: If the ball moves very quickly, it is hard to always keep the required distance to the ball, especially since the speed of the robots is limited during STOP. Therefore, it is sufficient if it is obvious to the referee that the robots try their best to follow the distance rule.

.Usage
The STOP command is used to pause the game after the ball crossed the field boundaries (including goals) or a foul occured as well as to prepare the start or resumption of the game after HALT, timeouts and automatic ball placement. The robot speed limit and the minimum distance to the ball allow the referee or assistant referee to place the ball safely and without interference.



==== Halt
.Definition
When the HALT command is issued, all robots have to brake immediately. During HALT, the robots are not allowed to move or manipulate the ball.

.Usage
The HALT command allows the referee to interrupt the game immediately whenever an emergency occurs (for example when a robot gets out of contol). It is
also used to recalibrate the vision software during a game if the vision expert considers it necessary and the referee agrees. Additionally, the referee is free to issue the HALT command at will.

The HALT command is always followed up by STOP.

=== Resuming The Game
To resume the game after a stoppage or start the game in the first place, the ball has to be placed at a certain position on the field first. The main referee or assistant referee is advised to use a so-called ball handler (a long, preferably black stick-like device) to move the ball.

In Division A, the ball will be placed automatically by the robots if the following command is a free kick or FORCE START (see <<Automatic Ball Placement>>).

// Chapter 5.5: ball handler
// Chapter 9.2: automatic ball placement

==== Kick-Off
.Definition
The ball has to be placed at the center of the field.

When the KICK-OFF command is issued, all robots have to move to their own half of the field excluding the center circle. However, one robot of the attacking team is also allowed to be inside the whole center circle. This robot will be referred to as the kicker. No robot is allowed to touch the ball.

When the NORMAL START command is issued, the kicker is allowed to shoot the ball. A goal may be scored directly from the kick-off.

When the ball is in play, the kicker may not touch the ball again until it has been touched by another robot or the game has been stopped. Also, the restrictions regarding the robot positions are lifted.

.Usage
Both half times as well as both extra time periods (if needed) start with a kick-off. Chapter <<Game preparation>> describes how to determine the attacking team.

Additionally, after a goal has been scored, the receiving team restarts the game with a kick-off.

// Chapter 8.2

==== Direct Free Kick
.Definition
The ball has to be placed inside the field with at least 100mm distance to the field boundaries and at least 700mm distance to the defense areas. The exact position of the ball is defined by the type of offense that led to the free kick.

When the DIRECT FREE KICK command is issued, robots of the attacking team are allowed to approach the ball while robots of the defending team still have to stay at least 500mm distance away from the ball (the same distance as in STOP). One robot of the attacking team is allowed to shoot the ball. This robot will be referred to as the kicker. A goal may be scored directly from the direct free kick.

When the ball is in play, the kicker may not touch the ball again until it has been touched by another robot or the game has been stopped. Also, the restrictions regarding the robot positions are lifted.

.Usage
Direct free kicks are used to restart the game after a <<Fouls, foul>> has occured. Additionally, <<Goal Kick, goal kicks>> and <<Corner Kick, corner kicks>> are mapped to direct free kicks.

==== Indirect Free Kick
.Definition
An indirect free kick behaves like a direct free kick, except: After an indirect free kick, a goal can only be scored if the ball touches a robot of the attacking team after the ball entered play and before it entering the goal. If the ball enters the goal without touching an attacking robot, it will be treated like it crossed the goal line outside the goal.

NOTE: A goal can only be scored if more than one attacking robot is involved or a robot of the defending team has touched the ball before the attacker shot the goal.

NOTE: In association football, it is sufficient if any player (including the keeper) touches the ball before it enters the goal. To discourage the teams to shoot directly at the goal and hope that the keeper touches it, the rules of the Small Size League require a second touch of an attacking robot.

.Usage
Indirect free kicks are used to restart the game after a <<Minor Offenses, minor offense>> has occured. Additionally, <<Throw-In, throw-ins>> are mapped to indirect free kicks.

==== Force Start
.Definition
When the FORCE START command is issued, the game is immediately resumed and both teams are allowed to manipulate the ball again.

.Usage
The referee can issue a STOP command followed by FORCE START if there is a clear lack of progress for at least 10 seconds while both teams are allowed to manipulate the ball. This is not the case if the ball is inside a defense area.

It can also be used to resume the game when the game had to be stopped and no team or both teams are at fault.

==== Penalty Shot
Chapter 14

=== Sanctions
==== Yellow Card
Chapter 12.4

==== Red Card
Chapter 12.4

==== Forced Forfeit
==== Disqualification


=== Special Commands

==== Automatic Ball Placement
Chapter 9.2

.Definition

.Usage

==== Shoot-Out
Appendix A.2

