== Referee Commands

=== Stopping The Game
==== Stop
.Definition
When the stop command is issued, all robots have to slow down to less than 1.5 m/s. Additionally, all robots have to keep at least 0.5 meters distance to the ball and are not allowed to <<Ball Manipulation, manipulate the ball>>.

NOTE: If the ball moves very quickly, it is hard to always keep the required distance to the ball, especially since the speed of the robots is limited during stop. Therefore, it is sufficient if it is obvious to the referee that the robots try their best to follow the distance rule.

.Usage
The stop command is used to pause the game after the ball crossed the <<Field Lines, field lines>> (including goals) or an offense occurred as well as to prepare the start or resumption of the game after halt, timeouts and automatic ball placement. The robot speed limit and the minimum distance to the ball allow the referee or assistant referee to place the ball safely and without interference.

==== Halt
.Definition
When the halt command is issued, no robot is allowed to move or <<Ball Manipulation, manipulate the ball>>.

There is a grace period of 2 seconds for the robots to brake.

.Usage
The halt command allows the referee to interrupt the game immediately whenever an emergency occurs (for example when a robot gets out of contol). It is
also used to recalibrate the vision software during a game if the vision expert considers it necessary and the referee agrees and for <<Robot Substitution, robot substitution>>. Additionally, the referee is free to issue the halt command at will.

The halt command is always followed up by stop.


=== Ball Placement
.Definition
After the game was stopped, the ball must be placed on the appropriate position, depending on the event that occurred.
The automatic ball placement is the preferred way to place the ball at the designated position on the field by the robots of the teams without human interaction.
If this is not possible, the <<Referee, referee>> places the ball manually.

No ball placement is required if all of the following constraints are fulfilled:

* The ball is closer than 1m to the designated position.
* The ball is inside the field.
* The ball is at least 0.7m away from any defense area.
* The ball is stationary.

In this case, the game can be continued as soon as all robots keep the required distance for <<Stop, stop>>.

A ball is considered placed successfully by the robots if

* no more than 30 seconds passed since the placement command
* there is no robot within 0.05 meters distance to the ball if the next command is a <<Free Kick, free kick>> for the placing team
* there is no robot within 0.5 meters distance to the ball if the next command is a <<Force Start, force start>>
* the ball is stationary
* the ball is at a position within 0.15 meters radius from the requested position

No further commands will be issued by the <<Game Controller, game controller>> until the automatic placement is complete.
The game will be continued by the <<Game Controller, game controller>> as soon as the ball is successfully placed, but not earlier than 2 seconds after the ball placement command has been issued.
A failed placement will result in a free kick for the opposing team.
If this team failed to place the ball as well, the ball is placed by the <<Referee, referee>> and game continues with the original command.

For each team a ball placement failure counter is incremented on each placement failure and decremented for successful placements. It can not get negative.

The non-placing team must not <<Ball Placement Interference, interfere the ball placement task>>.

.Usage
When the ball goes <<Ball In And Out Of Play, out of play>>, the following rules decide, if automatic ball placement is applied:

. The <<Referee, referee>> has to place the ball for all kickoffs and all penalty kicks
. For a <<Free Kick, free kick>>, the team that brings the ball <<Ball In And Out Of Play, into play>> must place the ball
. For a <<Force Start, force start>>, a team is drawn by chance and must place the ball
. The ball must be visible and must not be inside a field corner, a goal corner or behind the goal, before the ball placement starts
. The <<Referee, referee>> can decide to place the ball manually at any time
. The <<Referee, referee>> can decide to disable automatic ball placement for the rest of the game. TC/OC must agree with this decision
. When a teams placement failure counter reached 5, it is not allowed to place the ball for the rest of the game half. All free kicks that were a result of the ball leaving the field, are awarded to the opposing team. For all other rule violations or when both teams failed to place the ball, the ball is placed by the <<Referee, referee>>
. If no team can place the ball, the ball is placed by the <<Referee, referee>> or the <<Assistant Referee, assistant referee>>. Both the referee as well as the assistant referee are advised to use a so-called ball handler (a long, preferably black stick-like device) to move the ball.

NOTE: The ball may still be moving when the placement command is issued.

NOTE: The game commences directly after ball placement. The team receiving the ball may shoot immediately and leave the opposing team little time to arrange defensive actions if needed.

NOTE: It is allowed to enter the defense area during ball placement.

Ball placement is mandatory for all teams in division A.
Teams in division B may decide, at any time before or during the game, not to place the ball for the rest of the game by talking to the <<Referee, referee>>, who in turn tells the <<Game Controller Operator, game controller operator>> to disable ball placement for this team.
In this case, the team is allowed to bring the ball into play, after the ball was placed by the opposing team.
If the opposing team fails to place the ball or no team can place the ball, it is placed by the <<Referee, referee>> or the <<Assistant Referee, assistant referee>>.


=== Resuming The Game
After the ball has been placed, the game is resumed using one of the following commands.

==== Normal Start
.Definition
For two-staged referee commands, when normal start is sent, an attacker may <<Ball Manipulation, manipulate the ball>>. A match cannot be resumed directly via normal start.

.Usage
Normal start is used for <<Kick-Off, kick-offs>> and <<Penalty Kick, penalty kicks>>.

==== Kick-Off
.Definition
The ball has to be placed in the center of the field by the human referee.

When the kick-off command is issued, all robots have to move to their own half of the field excluding the <<Center Circle, center circle>>. However, one robot of the attacking team is also allowed to be inside the whole center circle. This robot will be referred to as the kicker. No robot is allowed to touch the ball.

When the <<Normal Start, normal start>> command is issued, the kicker is allowed to shoot the ball. A goal may be scored directly from the kick-off.

When the ball is <<Ball In And Out Of Play, in play>>, the kicker may not touch the ball until it has been touched by another robot or the game has been stopped (see <<Double Touch, double touch>>). Also, the restrictions regarding the robot positions are lifted.

.Usage
Both half times as well as both overtime periods (if needed) start with a kick-off. Chapter <<Match Preparation>> describes how to determine the attacking team.

Additionally, after a goal has been scored, the receiving team restarts the game with a kick-off.

==== Free Kick
.Definition
The ball placement position for a free kick depends on the event that led to the free kick. This position is valid if there is at least 0.2 meters distance to all <<Field Lines, field lines>> and 1 meter distance to either <<Defense Area, defense area>>. If an event requires the ball to be placed at a position that contravenes this rule, it has to be placed at the closest valid position instead.

When the free kick command is issued, robots of the attacking team are allowed to approach the ball while robots of the defending team still have to stay at least 0.5 meters distance away from the ball (the same distance as in stop). One robot of the attacking team is allowed to shoot the ball. This robot will be referred to as the kicker. A goal may be scored directly from the free kick.

When the ball is <<Ball In And Out Of Play, in play>>, the kicker may not touch the ball until it has been touched by another robot or the game has been stopped (see <<Double Touch, double touch>>). Also, the restrictions regarding the robot positions are lifted.

.Usage
Free kicks are used to restart the game after a <<Fouls, foul>> has occurred. Additionally, <<Goal Kick, goal kicks>> and <<Corner Kick, corner kicks>> are mapped to free kicks.

==== Force Start
.Definition
When the force start command is issued, the game is immediately resumed and both teams are allowed to approach and <<Ball Manipulation, manipulate the ball>> again.

.Usage
A neutral forced start is used in situations where no team is clearly in favor, such as:

* the game had to be stopped without a specific reason.
* both teams are at fault.

==== Penalty Kick
.Definition
The procedure of a penalty kick is as follows:

. The ball is placed by the human referee on the <<Penalty Mark, penalty mark>>.
. When the <<Penalty Kick, penalty>> command is issued
.. The defending keeper has to move to the goal line and keep touching it
.. One attacking robot is allowed to approach the ball but not allowed to touch the ball
.. All other robots have to be 1m behind the ball such that they do not interfere the penalty kick procedure at any time.
. When the <<Normal Start, normal start>> command is issued, the attacker is allowed to <<Ball Manipulation, manipulate the ball>>. The ball has to only move towards the opponent goal, as measured by its x coordinate in the coordinate system of <<Vision, SSL-Vision>>.
. When the ball is <<Ball In And Out Of Play, in play>>, the defending keeper may move freely again
. If the ball is still <<Ball In And Out Of Play, in play>> after 10 seconds, the game is stopped and then continued by a <<Goal Kick, goal kick>> for the defending team.

A goal is awarded if:

* the ball touches the inner surface of a goal wall or the ground of the goal of the defending team, starting from when the <<Normal Start, normal start>> command is issued
* the defending team violates any rule

A goal is not awarded if:

* the ball crosses any <<Field Lines, field lines>> outside the goal
* the defending keeper touches the ball such that the ball speed vector changes direction by at least 90 degrees in 2D space
* the attacking team violates any rule

NOTE: The restrictions defined for <<Scoring Goals, scoring goals>>, including the ball height limit of 0.15 meters, do not apply here.
Other rules like the <<Excessive Dribbling, excessive dribbling>> limitation for example do.

Additional time is allowed for a penalty kick to be taken at the end of each half or at the end of periods of overtime.

.Usage
Penalty Kicks are used to punish <<Unsporting Behavior, unsporting behavior>> and <<Multiple Defenders, multiple defenders>>.


=== Ball In And Out Of Play
When the match is <<Stopping The Game, stopped>>, the ball is considered *out of play* until it has been brought into play.

When the match is <<Resuming The Game, resumed>>, the ball is considered *in play* until the next stoppage occurs.
The match is resumed when

* <<Force Start, force start>> has been issued.
* the ball moved at least 0.05 meters following a <<Kick-Off, kick-off>>, <<Free Kick, free kick>> or <<Penalty Kick, penalty kick>>.
* 10 seconds passed following a <<Kick-Off, kick-off>>.
* 5 seconds (Division A) or 10 seconds (Division B) passed following a <<Free Kick, free kick>>.

NOTE: see <<Double Touch, double touch>> for the rationale of the 0.05 meter distance


=== Sanctions

==== Yellow Card
.Definition

If the yellow card is shown as a result of <<Unsporting Behavior, unsporting behavior>>, the referee may decide to immediately <<Halt, halt>> the match. In this case, the match continues with a free kick for the other team.

Upon receipt of a yellow card, the number of robots allowed on the field for the penalized team decreases by one. If, after this decrease, the team has more robots than permitted on the field, a robot must be <<Robot Substitution, taken out>>.

A yellow card does not lead to a stop automatically. If the the ball is <<Ball In And Out Of Play, in play>>, the team will have 10 seconds to <<Robot Substitution, automatically remove the robot>>. If a robot is not taken out within time, the game is stopped for <<Robot Substitution, manual substitution>>.

NOTE: This rule implies that after receiving a yellow card, the game might not be automatically stopped. However, the game will be stopped if the foul that led to the yellow card causes a game stoppage, e.g. dropping parts. Therefore, if one of those fouls occurred, the team is allowed to manually remove the robot.

NOTE: In 2020 no penalty will be given to the team that couldn't get the robot out of the field in time. Thus, the game shall be restarted using a force start. However, in 2021, if the robot gets manually substituted, the ball is placed on the mid line and 1.5 meters away from the teams defense area and the opposing team gets a free kick.

A team cannot score a goal while having more than the allowed number of robots on the field.

After 120 seconds of playing time (measured by the game controller), the yellow card expires and the number of allowed robots is increased by one. The team may <<Robot Substitution, put a robot back in>> during the next opportunity.

When a team has two not yet expired yellow cards and receives another yellow card, this card will be turned into a red card instead.

.Usage
Yellow cards are used to punish teams that committed multiple <<Fouls, fouls>>.

Yellow cards can also be given by the referee to punish <<Fouls, fouls>> or <<Unsporting Behavior,unsporting behavior>>.

==== Red Card
.Definition
A red card behaves like a <<Yellow Card, yellow card>>, except: It does not expire until the end of the game.

.Usage
Red cards are given by the referee to punish severe <<Fouls, fouls>> or <<Unsporting Behavior,unsporting behavior>>.

NOTE: For example, serious violent contact by the robots or disrespectful behavior towards the referees can result in a red card.


==== Forced Forfeit
.Definition
A Forced forfeit means that a team instantly loses the current game with a score of 0 to 10.

.Usage
A team can be forced to forfeit if it is unable to play with at least one robot that satisfies the rules.

A team can only be forced to forfeit in agreement with members of the <<Technical Committee, technical committee>> and the <<Organizing Committee, organizing committee>>.

==== Disqualification
.Definition
A Disqualification means that a team immediately drops out of the tournament and places last. It will not be eligible to receive any trophies.

.Usage
A team can be disqualified if members of this team don't follow safety guidelines, rules of the venue or commit similarly severe offenses.

A team can only be disqualified in agreement with members of the <<Technical Committee, technical committee>> and the <<Organizing Committee, organizing committee>>.
