== Robot Substitution
.Definition
Robots are substituted by the <<Robot Handler, robot handler>> of the respective team. No other team member is allowed to take robots out or put robots in.

The <<Robot Handler, robot handler>> should prefer to use long sleeves and colors that won't interfere with the vision system.

Robots can always be taken in and out during game play without notifying the <<Referee, referee>> if all the following conditions are met:

. The robot is at least partially inside the <<Field Surface, field margin>>.
. The robot is at a distance from the <<Halfway Line, halfway line>> that must not exceed 1 meter.
. The ball must be at least 0.5 meters away from the robot.

Additionally, robots can be taken out from any position on request using the procedure below:

. The <<Robot Handler, robot handler>> requests robot substitution at any time.
. The <<Game Controller, game controller>> will <<Halt, halt>> the game at the next opportunity.
. The <<Robot Handler, robot handler>> may enter the field and touch robots now.
. The <<Robot Handler, robot handler>> takes robots out.
. The <<Robot Handler, robot handler>> informs the <<Referee, referee>> when done.
. When both teams finished the robot substitution, the <<Referee, referee>> informs the <<Game Controller Operator, game controller operator>>.
. The <<Game Controller Operator, game controller operator>> performs a <<Stop, stop>> followed by continuing the game.

The maximum allowed number of robots of the team on the field must not be exceeded at any time when putting robots in.

.Usage
Robots can be substituted for any reason.
A substitution grants the team 10 seconds to take robots out. After that time, a new substitution is started.
Each team has 5 free substitutions per halftime.
Every additional substitution will result in an <<Excessive Robot Substitutions, excessive robot substitutions foul>> for the team.

A robot substitution intent can be made by:

. A <<Robot Handler, robot handler>> by informing the <<Game Controller Operator, game controller operator>> who in turn enters the intent into the <<Game Controller, game controller>>.
. A <<Robot Handler, robot handler>> by using the <<Remote Control, remote control>>, if provided.
. A team software by sending a request to the <<Game Controller, game controller>>.
. The <<Game Controller, game controller>> itself if a team exceeds the maximum number of robots (for example after a team receives a <<Yellow Card, yellow>> or <<Red Card, red card>>).

If the game was halted due to a substitution intent by a team, at least one robot must be taken out by this team. A substitution intent can be revoked unless the game was not already halted for substitution.

If a robot substitution intent for either team is present just before the game would continue after ball placement, the <<Game Controller, game controller>> automatically <<Halt, halts>> the game.
