== Robot Substitution
.Definition
Robots are substituted by the <<Robot Handler, robot handler>> of the respective team. No other team member is allowed to take robots out or put robots in.

. The <<Robot Handler, robot handler>> must preferably not wear colors that may interfere with the vision system.
.. If non-stop robot interchange is allowed (Division A), the <<Robot Handler, robot handler>> should preffer using long sleeves.

. A <<Robot Handler, robot handler>> who's team is marked for robot substitution performs at least one of the following operations in the given order.
.. Put robots in. The maximum allowed number of robots of the team on the field must not be exceeded.
.. Put robots in during game play (Division A only). If the ball is at least 2 meters away from the midline, the robot can be placed in it without notifying the <<Referee, referee>>.
.. Take robots out. If a robot that is taken out is closer than 1 meter to the intersection of the halfway line with one of the touch lines, another robot can be put in right away. Otherwise the robot handler has to wait until the next substitution opportunity.
.. Take robots out during game play (Division A only). If a robot is at the midline and the ball is at least 2 meters away from the midline, the robot can be removed without notifying the <<Referee, referee>>.
. If one of the robots taken out is the keeper, the <<Robot Handler, robot handler>> tells the <<Game Controller Operator, game controller operator>> the id of the robot that takes over the keeper role.
. The <<Robot Handler, robot handler>> informs the <<Referee, referee>> when done.
. When both teams finished the robot substitution, the <<Referee, referee>> informs the <<Game Controller Operator, game controller operator>>.
. The <<Game Controller Operator, game controller operator>> performs a <<Stop, stop>> followed by continuing the game.

.Usage
Robots can be substituted for any reason. There is no limit on the number of substitutions.

A robot substitution intent can be made by:

. A <<Robot Handler, robot handler>> by informing the <<Game Controller Operator, game controller operator>> who in turn enters the intent into the <<Game Controller, game controller>>.
. A team software by sending a request to the <<Game Controller, game controller>>.
. The <<Game Controller, game controller>> itself if a team exceeds the maximum number of robots (for example after a team receives a <<Yellow Card, yellow>> or <<Red Card, red card>>).

If the game was halted due to a substitution intent by a team, at least one substitution (taking a robot out or putting one in) must be performed by this team. A substitution intent can be revoked unless the game was not already halted for substitution.

If a robot substitution intent for either team is present just before the game would continue after ball placement, the <<Game Controller, game controller>> automatically <<Halt, halts>> the game.
