== Robot Substitution
Robots can be substituted for any reason. There is no limit on the number of substitutions.

Robots are substituted by the <<Robot Handler, robot handler>> of the respective team. No other team member is allowed to take robots out or put robots in.

A robot substitution consists of two actions, <<Taking A Robot Out, taking a robot out>> and <<Putting A Robot In, putting a robot in>>. If the robot to be taken out is closer than 1 meter to the intersection of the halfway line with one of the touch lines, another robot can be put in right away. Otherwise, the <<Robot Handler, robot handler>> has to wait until the next stoppage of the game (after the ball placement has been completed).

If the robot to be taken out is the keeper, the <<Robot Handler, robot handler>> tells the <<Referee, referee>> the id of the robot that takes over the keeper role. This information is forwarded to the <<Game Controller Operator, game controller operator>>.

=== Taking A Robot Out

. The <<Robot Handler, robot handler>> informs the <<Referee, referee>> that he intends to take a robot out.
. The referee forwards this request to the <<Game Controller Operator, game controller operator>>, so that he can pause the <<Automatic Referee, automatic referee>>.
. After the next ball placement (manual or automatic), the <<Halt, halt>> command is issued and the <<Robot Handler, robot handler>> is allowed to take the robot out.

=== Putting A Robot In

. The <<Robot Handler, robot handler>> informs the <<Referee, referee>> that he intends to put a robot in.
. The referee forwards this request to the <<Game Controller Operator, game controller operator>>, so that he can pause the <<Automatic Referee, automatic referee>>.
. After the next ball placement (manual or automatic), the <<Halt, halt>> command is issued and the <<Robot Handler, robot handler>> is allowed to put the robot in.
