== Robot Substitution
Robots can be substituted for any reason. There is no limit on the number of substitutions.

Robots are substituted by the <<Robot Handler, robot handler>> of the respective team. No other team member is allowed to take robots out or put robots in.

A robot substitution intent can be made by:

. A <<Robot Handler, robot handler>> by informing the <<Game Controller Operator, game controller operator>> who in turn enters the intent into the <<Game Controller, game controller>>.
. A team software by sending a request to the <<Game Controller, game controller>>.
. The <<Game Controller, game controller>> itself if a team exceeds the maximum number of robots.

If a robot substitution intent for either team is present just before the game would continue after ball placement, the <<Game Controller, game controller>> automatically <<Halt, halts>> the game.

=== Procedure

. Each <<Robot Handler, robot handler>> who's team is marked for robot substitution performs at least one of the following operations in the given order. Each operation can be repeated:
1. Put a robot in. The maximum allowed number of robots of the team on the field must not be exceeded.
2. Take a robot out. If this robot is closer than 1 meter to the intersection of the halfway line with one of the touch lines, another robot can be put in right away.
. If one of the robots taken out is the keeper, the <<Robot Handler, robot handler>> tells the <<Game Controller Operator, game controller operator>> the id of the robot that takes over the keeper role.
. The <<Robot Handler, robot handler>> informs the <<Referee, referee>> when done.
. When both teams finished the robot substitution, the <<Referee, referee>> informs the <<Game Controller Operator, game controller operator>>.
. The <<Game Controller Operator, game controller operator>> performs a <<Stop, stop>> followed by continuing the game.

NOTE: If a robot is not taken out within 1 meter to the intersection of the halfway line with one of the touch lines, the <<Robot Handler, robot handler>> has to wait until the next substitution opportunity.

NOTE: If the game was halted due to a substitution intent by a team, at least one substitution (taking a robot out or putting one in) must be performed by this team. A substitution intent can be revoked unless the game was not already halted for substitution.
