== Robot Substitution
.Definition
Robots are substituted by the <<Robot Handler, robot handler>> of the respective team. No other team member is allowed to take robots out or put robots in.

. Robot substitution during game play:
.. The <<Robot Handler, robot handler>> should prefer to use long sleeves and colors that won't interfere with the vision system.
.. A robot can only be substituted while obeying the following specifications:
... Is at least on top of any touch line, if possible the robot can also be placed beyond the field boundaries
... At a distance from the halfway line that must not exceed 30 centimeters
.. A <<Robot Handler, robot handler>> who's team is marked for robot substitution performs the following operations.
... Put robots in. If the ball is at least 2 meters away from the halfway line, the robot can be substituted without notifying the <<Referee, referee>>.
... Take robots out. If the robot is placed at the previous specified position and the ball is at least 2 meters away from the halfway line, the robot can be removed without notifying the <<Referee, referee>>.

. Robot substitution on next stoppage:
.. A <<Robot Handler, robot handler>> who's team is marked for robot substitution performs the following operations.
... Put robots in. The maximum allowed number of robots of the team on the field must not be exceeded.
... Take robots out. If a robot that is taken out is closer than 1 meter to the intersection of the halfway line with one of the touch lines, another robot can be put in right away. Otherwise the robot handler has to wait until the next substitution opportunity.
... The <<Robot Handler, robot handler>> informs the <<Referee, referee>> when done.
... When both teams finished the robot substitution, the <<Referee, referee>> informs the <<Game Controller Operator, game controller operator>>.
... The <<Game Controller Operator, game controller operator>> performs a <<Stop, stop>> followed by continuing the game.

. If one of the robots taken out is the keeper, the <<Robot Handler, robot handler>> tells the <<Game Controller Operator, game controller operator>> the id of the robot that takes over the keeper role.


.Usage
Robots can be substituted for any reason. There is no limit on the number of substitutions.

A robot substitution intent can be made by:

. A <<Robot Handler, robot handler>> by informing the <<Game Controller Operator, game controller operator>> who in turn enters the intent into the <<Game Controller, game controller>>.
. A team software by sending a request to the <<Game Controller, game controller>>.
. The <<Game Controller, game controller>> itself if a team exceeds the maximum number of robots (for example after a team receives a <<Yellow Card, yellow>> or <<Red Card, red card>>).
. *(Division A only)* If a robot needs to be taken out and it is not in the mid line, a timeout needs to be taken in order for the team to remove the robot from the field. If a team is out of timeouts, it will still be able to take the robot out, however, it will not be able to use any remaining timeout time, the robot must be removed from the field as fast as possible.

If the game was halted due to a substitution intent by a team, at least one substitution (taking a robot out or putting one in) must be performed by this team. A substitution intent can be revoked unless the game was not already halted for substitution.

If a robot substitution intent for either team is present just before the game would continue after ball placement, the <<Game Controller, game controller>> automatically <<Halt, halts>> the game.
